import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer,request} from 'node:http';
import {createAaroUsageFromEnv} from '../runtime/aaro-usage-assembly.mjs';
import {conversion,receiptNow} from './supplier-receipt-fixture.mjs';
const key='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const manifest={protocol:'aaro-subrouter-usage-v1',product:'aaro',mode:'test',keyReference:key,tariffVersion:'fixture-NOT-A-PRICE',acceptanceReceiptSHA256:'a'.repeat(64),totalCapNativeCnyMicros:50000000,maxCallNativeCnyMicros:100,models:{qwen:{model:'QwenFixture',maxInputTokens:100,maxOutputTokens:32}}};
const binding={product:'aaro',mode:'test',keyReference:key,tokenId:123,accountUserId:21872,modelProviders:{QwenFixture:'leapnode'}};
const base={AARO_FINANCE_ENABLED:'true',AARO_FINANCIAL_ACCEPTANCE_VERIFIED:'true',AARO_PROVIDER_ACCEPTANCE_VERIFIED:'true',AARO_WEBHOOK_INGRESS_VERIFIED:'true',AARO_SUBROUTER_MANIFEST:JSON.stringify(manifest),AARO_SUPPLIER_BINDING_JSON:JSON.stringify(binding),AARO_SUPPLIER_CONVERSION_JSON:JSON.stringify(conversion),AARO_SUBROUTER_ACCOUNT_ACCESS_TOKEN:'OfflineFixtureManagementToken00000',SUPABASE_SECRET_KEY:'sb_secret_OFFLINEFIXTURENOTREALKEY',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_OFFLINEFIXTURENOTREALKEY',AARO_BRIDGE_KEY:'OfflineFixtureBridgeSecret00000000000000000'};
async function invoke(env){
 let calls=0;const ingress=createAaroUsageFromEnv({env,clock:()=>receiptNow,fetchImpl:async()=>{calls++;return Response.json({id:'invalid'});}});
 const server=createServer((req,res)=>void ingress.handle(req,res));await new Promise(done=>server.listen(0,'127.0.0.1',done));
 try{const status=await new Promise((done,reject)=>{const req=request({host:'127.0.0.1',port:server.address().port,path:'/api/aaro/usage',method:'POST',headers:{host:'apiwild.com',origin:'https://apiwild.com','x-forwarded-proto':'https','x-aaro-bridge':base.AARO_BRIDGE_KEY,authorization:'Bearer FixtureToken','content-type':'application/json'}},res=>{res.resume();res.on('end',()=>done(res.statusCode));});req.on('error',reject);req.end(JSON.stringify({action:'reserve',protocol:manifest.protocol,product:'aaro',owner:'test:supabase:bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',mode:'test',keyReference:key,tariffVersion:manifest.tariffVersion,acceptanceReceiptSHA256:manifest.acceptanceReceiptSHA256,model:'QwenFixture',requestKey:'FixtureRequestKey0001',payloadHash:'b'.repeat(64),maximumInputTokens:100,maximumOutputTokens:32,totalCapNativeCnyMicros:50000000}));});return {status,calls};}finally{await new Promise(done=>server.close(done));}
}
await test('complete synthetic accepted assembly verifies customer before reserving, without supplier access',async()=>{const r=await invoke(base);assert.equal(r.status,403);assert.equal(r.calls,1);});
await test('each acceptance switch and required dedicated secret fails closed without reads',async()=>{for(const field of ['AARO_FINANCIAL_ACCEPTANCE_VERIFIED','AARO_PROVIDER_ACCEPTANCE_VERIFIED','AARO_WEBHOOK_INGRESS_VERIFIED','AARO_SUBROUTER_ACCOUNT_ACCESS_TOKEN','SUPABASE_SECRET_KEY','AARO_BRIDGE_KEY'])assert.deepEqual(await invoke({...base,[field]:''}),{status:503,calls:0});});
await test('known enterprise key UUID or supplier token cannot be reused for AARO',async()=>{for(const enterprise of [{[key]:{tokenId:999}},{'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb':{tokenId:binding.tokenId}}])assert.deepEqual(await invoke({...base,APIWILD_SUPPLIER_BINDINGS_JSON:JSON.stringify(enterprise)}),{status:503,calls:0});});
await test('wrong cap, mode, product and unsupported/mismatched model families remain closed',async()=>{for(const patch of [{product:'apiwild'},{totalCapNativeCnyMicros:100000000},{mode:'live'},{models:{unknown:{model:'QwenFixture',maxInputTokens:100,maxOutputTokens:32}}}])assert.deepEqual(await invoke({...base,AARO_SUBROUTER_MANIFEST:JSON.stringify({...manifest,...patch})}),{status:503,calls:0});});
