import test from 'node:test';
import assert from 'node:assert/strict';
import { createCustomerKeyRpc } from '../runtime/customer-key-rpc.mjs';
import { createGatewayRpc, SUPABASE_ORIGIN } from '../runtime/supabase-gateway-rpc.mjs';
import { createGatewayIngress } from '../runtime/gateway-ingress.mjs';
import { gatewayPayloadFingerprint } from '../runtime/gateway-service.mjs';
const USER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',KEY='cccccccc-cccc-4ccc-8ccc-cccccccccccc',BUDGET='dddddddd-dddd-4ddd-8ddd-dddddddddddd';
const SECRET='sb_secret_syntheticOnlyNotReal000001', PUBLIC='sb_publishable_syntheticOnlyNotReal000001', TOKEN='aw_test_'+'a'.repeat(64), SESSION='Bearer synthetic.session.signature';
const meta=()=>({id:KEY,customer_id:USER,billing_mode:'test',scopes:['chat'],daily_limit_usd_micros:100,total_limit_usd_micros:1000,expires_at:new Date(Date.now()+86400000).toISOString(),revoked_at:null});
function keys(){return createCustomerKeyRpc({supabaseOrigin:SUPABASE_ORIGIN,secretKey:SECRET,billingMode:'test',verifyOwner:async({authorization})=>{assert.equal(authorization,SESSION);return {customerId:USER,billingMode:'test'};},fetchImpl:async(url,init)=>{const p=JSON.parse(init.body);if(url.endsWith('_list'))return Response.json([meta()]);if(url.endsWith('_issue'))return Response.json({...meta(),id:p.p_id,scopes:p.p_scopes,daily_limit_usd_micros:p.p_daily_limit,total_limit_usd_micros:p.p_total_limit,expires_at:p.p_expires_at});if(url.endsWith('_revoke'))return Response.json({...meta(),revoked_at:new Date().toISOString()});return Response.json(meta());}});}
function fixture(patch={}){
 const keyClient=keys(),calls=[];const rpc={verifyOwner:async()=>({customerId:USER,billingMode:'test'}),verifyKeyOwner:async raw=>{const c=await keyClient.authenticate(raw);return {customerId:c.customerId,billingMode:c.billingMode,keyId:c.keyId};}};
 const service={execute:async(...args)=>{calls.push(args);return {ok:true,id:'fixture',result:{text:'answer',model:'fixture-model',usage:{prompt_tokens:2,completion_tokens:3}}};}};
 const ingress=createGatewayIngress({rpc,keys:keyClient,service,selectQuote:async()=>({providerBudgetId:BUDGET,model:'fixture-model',rateVersion:'v1',reservedUsdMicros:100,reservedCnyMicros:10}),origin:'https://apiwild.com',enabled:true,...patch});return {ingress,calls};
}
const request=(path='/v1/chat/completions',body={model:'fixture-model',messages:[{role:'user',content:'fixture'}]},patch={})=>new Request('https://apiwild.com'+path,{method:'POST',headers:{authorization:'Bearer '+TOKEN,'content-type':'application/json','idempotency-key':'fixture_request_01'},body:JSON.stringify(body),...patch});
test('API request uses verified key identity and server quote; exact envelope fingerprint binds reservation',async()=>{const f=fixture();const r=await f.ingress.handle(request());assert.equal(r.status,200);const data=await r.json();assert.equal(data.object,'chat.completion');assert.equal(data.usage.total_tokens,5);assert.equal(r.headers.get('cache-control'),'private, no-store');const [context,quote,payload]=f.calls[0];assert.equal(context.keyId,KEY);assert.equal(quote.keyId,KEY);assert.equal(quote.payloadHash,gatewayPayloadFingerprint(payload));assert.equal(quote.reservedUsdMicros,100);});
test('native request accepts verified session and never fabricates key association',async()=>{const f=fixture();const r=await f.ingress.handle(request('/api/gateway',undefined,{headers:{authorization:SESSION,'content-type':'application/json','idempotency-key':'fixture_request_01'}}));assert.equal(r.status,200);assert.equal(f.calls[0][1].keyId,null);});
test('unconfigured enable gate does not authenticate, select or dispatch',async()=>{const f=fixture({enabled:false});assert.equal((await f.ingress.handle(request())).status,503);assert.equal(f.calls.length,0);});
test('caller prices, tools, streaming, malformed bounds and omitted idempotency cannot dispatch',async()=>{for(const patch of [{reservedUsdMicros:1},{tools:[]},{stream:true},{max_tokens:0},{messages:[{role:'tool',content:'x'}]}]){const f=fixture();assert.ok((await f.ingress.handle(request('/v1/chat/completions',{model:'fixture-model',messages:[{role:'user',content:'x'}],...patch}))).status>=400);assert.equal(f.calls.length,0);}const f=fixture();assert.equal((await f.ingress.handle(request('/v1/chat/completions',undefined,{headers:{authorization:'Bearer '+TOKEN,'content-type':'application/json'}}))).status,400);});
test('API surface rejects session bearer, origins, query strings and forged authentication headers',async()=>{for(const [path,headers] of [['/v1/chat/completions',{authorization:SESSION}],['/v1/chat/completions?x=1',{}],['/v1/chat/completions',{origin:'https://example.invalid'}],['/v1/chat/completions',{'oai-authenticated-user-id':USER}]]){const f=fixture();const h={authorization:'Bearer '+TOKEN,'content-type':'application/json','idempotency-key':'fixture_request_01',...headers};assert.ok((await f.ingress.handle(request(path,undefined,{headers:h}))).status>=400);assert.equal(f.calls.length,0);}});
test('key lifecycle uses session verifier and protects one-time response from caching',async()=>{const f=fixture();const list=await f.ingress.handle(new Request('https://apiwild.com/api/keys',{headers:{authorization:SESSION}}));assert.equal(list.status,200);const issued=await f.ingress.handle(request('/api/keys',{scopes:['chat'],dailyLimitUsdMicros:100,totalLimitUsdMicros:1000,expiresAt:new Date(Date.now()+86400000).toISOString()},{headers:{authorization:SESSION,'content-type':'application/json'}}));assert.equal(issued.status,201);assert.match((await issued.json()).key,/^aw_test_[a-f0-9]{64}$/);assert.equal(issued.headers.get('cache-control'),'private, no-store');assert.equal(f.calls.length,0);});
test('held service result cannot leak partial provider output or suggest retries',async()=>{const f=fixture({service:{execute:async()=>({ok:false,result:{text:'private'}})}});const r=await f.ingress.handle(request());assert.equal(r.status,503);assert.deepEqual(await r.json(),{status:'awaiting-reconciliation',automaticRetry:false});});
test('body byte limit and content encoding rejected before dispatch',async()=>{for(const [body,headers] of [{body:'x'.repeat(65537),headers:{'content-type':'application/json'}},{body:'{}',headers:{'content-type':'application/json','content-encoding':'gzip'}}].map(x=>[x.body,x.headers])){const f=fixture();const r=await f.ingress.handle(new Request('https://apiwild.com/v1/chat/completions',{method:'POST',headers:{authorization:'Bearer '+TOKEN,...headers},body}));assert.ok(r.status>=400);assert.equal(f.calls.length,0);}});
test('real branded key verifier mints gateway context; forged verifier or copied owner cannot reserve',async()=>{
 const verifier=keys();const calls=[];const config={supabaseOrigin:SUPABASE_ORIGIN,secretKey:SECRET,publishableKey:PUBLIC,billingMode:'test',keyVerifier:verifier,fetchImpl:async(...args)=>{calls.push(args);throw Error('must not call');}};
 assert.throws(()=>createGatewayRpc({...config,keyVerifier:{authenticate:async()=>({customerId:USER,keyId:KEY})}}));const rpc=createGatewayRpc(config);const context=await rpc.verifyKeyOwner({authorization:'Bearer '+TOKEN,capability:'chat'});assert.equal(context.keyId,KEY);
 const reservation={keyId:KEY,providerBudgetId:BUDGET,requestKey:'fixture_request_01',payloadHash:'a'.repeat(64),capability:'chat',model:'fixture-model',rateVersion:'v1',reservedUsdMicros:100,reservedCnyMicros:10};
 assert.throws(()=>rpc.reserve({...context},reservation));assert.throws(()=>rpc.reserve(context,{...reservation,keyId:null}));assert.throws(()=>rpc.reserve(context,{...reservation,capability:'code'}));assert.equal(calls.length,0);
});

test('production HTTP mount routes API WILD keys through owned gateway, rejecting forged adapters',async()=>{
 const {createGatewayHttp}=await import('../runtime/gateway-http.mjs');const {createPreparationServer}=await import('../preparation-server.mjs');const {request:http}=await import('node:http');
 assert.throws(()=>createGatewayHttp({ingress:{handle(){}}}));assert.throws(()=>createPreparationServer({gatewayHttp:{handle(){}}}));
 const f=fixture(),server=createPreparationServer({gatewayHttp:createGatewayHttp({ingress:f.ingress})});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const call=host=>new Promise((resolve,reject)=>{const req=http({host:'127.0.0.1',port:server.address().port,path:'/api/keys',headers:{host,authorization:SESSION}},res=>{let body='';res.on('data',x=>body+=x);res.on('end',()=>resolve({status:res.statusCode,body:JSON.parse(body)}));});req.on('error',reject);req.end();});
 try{const r=await call('apiwild.com');assert.equal(r.status,200);assert.equal(r.body.keys[0].id,KEY);assert.equal((await call('evil.test')).status,403);assert.equal(f.calls.length,0);}finally{await new Promise(r=>server.close(r));}
});

test('authenticated playground reports configured modes without supplier secrets',async()=>{const f=fixture({playgroundModels:[{model:'fixture-model',capability:'research',maxOutputTokens:1024}]});const r=await f.ingress.handle(new Request('https://apiwild.com/api/gateway',{headers:{authorization:SESSION}}));assert.equal(r.status,200);assert.deepEqual(await r.json(),{inferenceConfigured:true,streaming:false,externalTools:false,models:[{model:'fixture-model',capability:'research',maxOutputTokens:1024}]});assert.equal(f.calls.length,0);});
test('playground modes reach owned service and no-credit error is clear without retry',async()=>{const {GatewayError}=await import('../runtime/supabase-gateway-rpc.mjs');for(const mode of ['chat','code','research']){const f=fixture();const response=await f.ingress.handle(request('/api/gateway',{mode,model:'fixture-model',messages:[{role:'user',content:'prompt'}],stream:false},{headers:{authorization:SESSION,'content-type':'application/json','idempotency-key':'playground_request_01'}}));assert.equal(response.status,200);assert.equal(f.calls[0][1].capability,mode);}const f=fixture({service:{execute:async()=>{throw new GatewayError('gateway_customer_limit',402);}}});const r=await f.ingress.handle(request('/api/gateway',undefined,{headers:{authorization:SESSION,'content-type':'application/json','idempotency-key':'playground_request_01'}}));assert.equal(r.status,402);assert.equal((await r.json()).code,'gateway_customer_limit');});
