import test from 'node:test';import assert from 'node:assert/strict';import {createHash}from'node:crypto';
import {createNativeCustomerApi}from'../runtime/native-customer-api.mjs';import {createNativeAuth}from'../runtime/subrouter-native-auth.mjs';import {createNativeSessionStore}from'../runtime/native-session-store.mjs';
import {createNativeAuthHttp}from'../runtime/native-auth-http.mjs';import {createPreparationServer}from'../preparation-server.mjs';import {request as httpRequest}from'node:http';
const ORIGIN='https://apiwild.com',STATION='https://apiwild.subrouter.ai',TOKEN='sk-syntheticNativeCustomerKey000001';
async function fixture(patch={}){
 const calls=[],store=createNativeSessionStore(),handle='a'.repeat(64);await store.put(createHash('sha256').update(handle).digest('hex'),{userId:2,sessionCookie:'session=private',expiresAt:Date.now()+60000});
 const fetchImpl=async(url,init)=>{calls.push({url,init});assert.equal(init.headers.cookie,'session=private');assert.equal(init.headers['New-Api-User'],'2');if(patch.handler)return patch.handler(url,init);
  const path=new URL(url).pathname;let data=path.endsWith('/self')?{id:2,username:'native',quota:500000}:path.endsWith('/models')?[{model_name:'fixture-model',enabled:true}]:path.endsWith('/create')?{key:TOKEN}:path.endsWith('/list')?[{id:11,name:'key',key:TOKEN,status:1}]:{};return Response.json({success:true,data});};
 const auth=createNativeAuth({enabled:true,stationOrigin:STATION,customerOrigin:ORIGIN,sessionStore:store,fetchImpl});
 const api=createNativeCustomerApi({auth,enabled:true,keyWritesEnabled:true,fetchImpl,...patch});
 const req=(operation,body,method=body?'POST':'GET')=>new Request(ORIGIN+'/api/native/customer/'+operation,{method,headers:{cookie:'__Host-apiwild_native='+handle,origin:ORIGIN,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return{api,calls,req,store,fetchImpl};
}
const create=()=>({name:'project',models:['fixture-model'],quotaUsdCents:1000,expiresAt:new Date(Date.now()+86400000).toISOString()});
test('native key creation verifies session/model and returns only one-time customer key',async()=>{const f=await fixture();const r=await f.api.handle(f.req('keys',create()));assert.equal(r.status,201);const data=await r.json();assert.equal(data.data.key,TOKEN);assert.equal(data.data.baseUrl,ORIGIN+'/v1');const p=JSON.parse(f.calls.find(c=>c.url.endsWith('/create')).init.body);assert.equal(p.type,'normal');assert.equal(p.remain_quota,5000000);assert.equal(p.unlimited_quota,false);assert.equal(p.model_limits,'fixture-model');assert.ok(!JSON.stringify(data).includes('session=private'));assert.equal(r.headers.get('cache-control'),'private, no-store');});
test('native key list metadata never reveals raw key and delete binds current customer list',async()=>{const f=await fixture();const list=await f.api.handle(f.req('keys'));assert.ok(!(await list.text()).includes(TOKEN));const deleted=await f.api.handle(f.req('keys/11',undefined,'DELETE'));assert.equal(deleted.status,200);assert.equal(f.calls.at(-1).init.method,'DELETE');const missing=await f.api.handle(f.req('keys/12',undefined,'DELETE'));assert.equal(missing.status,404);});
test('wrong origin, unlisted models, injected quota or customer ID cannot create keys',async()=>{for(const patch of [{models:['other']},{quotaUsdCents:0},{customerId:9},{models:['fixture-model','fixture-model']}]){const f=await fixture();const r=await f.api.handle(f.req('keys',{...create(),...patch}));assert.ok(r.status>=400);assert.equal(f.calls.filter(c=>c.url.endsWith('/create')).length,0);}const f=await fixture();const r=await f.api.handle(new Request(ORIGIN+'/api/native/customer/keys',{method:'POST',headers:{origin:'https://evil.invalid','content-type':'application/json'},body:JSON.stringify(create())}));assert.equal(r.status,403);assert.equal(f.calls.length,0);});
test('key mutations and customer API independently default disabled',async()=>{const f=await fixture({keyWritesEnabled:false});assert.equal((await f.api.handle(f.req('keys',create()))).status,503);assert.equal(f.calls.length,0);const g=await fixture({enabled:false});assert.equal((await g.api.handle(g.req('account'))).status,503);assert.equal(g.calls.length,0);});
test('native identity mismatch prevents key creation and billing callback',async()=>{const f=await fixture({handler:()=>Response.json({success:true,data:{id:9}})});assert.equal((await f.api.handle(f.req('keys',create()))).status,403);assert.equal(f.calls.length,1);});
test('billing delegates only verified native customer session and never grants local credits',async()=>{let seen;const f=await fixture({billingFactory:s=>{seen=s;return{read:async()=>({currency:'USD',creditsGranted:false}),checkout:async input=>({url:'https://checkout.stripe.com/fixture',creditsGranted:false,...input})};}});const r=await f.api.handle(f.req('billing/checkout',{amountCents:1000,currency:'USD'}));assert.equal(r.status,200);assert.equal(seen.userId,2);assert.equal(seen.sessionCookie,'session=private');const data=await r.json();assert.equal(data.data.creditsGranted,false);assert.ok(!JSON.stringify(data).includes('session=private'));});
test('ambiguous creation never retries or exposes upstream arbitrary data',async()=>{const f=await fixture({handler:(url)=>{if(url.endsWith('/self'))return Response.json({success:true,data:{id:2}});if(url.endsWith('/models'))return Response.json({success:true,data:['fixture-model']});throw Error(TOKEN);}});const r=await f.api.handle(f.req('keys',create()));assert.equal(r.status,503);assert.ok(!(await r.text()).includes(TOKEN));assert.equal(f.calls.filter(c=>c.url.endsWith('/create')).length,1);});
test('real HTTP mount connects native customer key creation, relay and usage without a duplicate ledger',async()=>{
 const f=await fixture();let relayCalls=0;
 const port=createNativeAuthHttp({enabled:true,customerOperationsEnabled:true,keyWritesEnabled:true,relayEnabled:true,allowedModels:['fixture-model'],sessionStore:f.store,fetchImpl:async(url,init)=>{
  if(url==='https://subrouter.ai/v1/chat/completions'){relayCalls++;assert.equal(init.headers.authorization,'Bearer '+TOKEN);return Response.json({id:'receipt',model:'fixture-model',choices:[{message:{role:'assistant',content:'answer'},finish_reason:'stop'}],usage:{prompt_tokens:2,completion_tokens:3}});}return f.fetchImpl(url,init);
 }});const server=createPreparationServer({nativeAuthHttp:port});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const call=(path,body,extra={})=>new Promise((resolve,reject)=>{const req=httpRequest({host:'127.0.0.1',port:server.address().port,path,method:body?'POST':'GET',headers:{host:'apiwild.com',origin:ORIGIN,cookie:'__Host-apiwild_native='+'a'.repeat(64),'content-type':'application/json',...extra}},res=>{let text='';res.on('data',x=>text+=x);res.on('end',()=>resolve({status:res.statusCode,data:JSON.parse(text)}));});req.on('error',reject);req.end(body?JSON.stringify(body):undefined);});
 try{const created=await call('/api/native/customer/keys',create());assert.equal(created.status,201);assert.equal(created.data.data.key,TOKEN);const relay=await call('/v1/chat/completions',{model:'fixture-model',messages:[{role:'user',content:'fixture'}],max_tokens:32},{authorization:'Bearer '+TOKEN,'idempotency-key':'fixture_native_http_01'});assert.equal(relay.status,200);assert.equal(relay.data.usage.total_tokens,5);assert.equal(relayCalls,1);assert.equal((await call('/api/native/customer/usage')).status,200);assert.equal((await call('/health/ready')).status,503);}finally{await new Promise(resolve=>server.close(resolve));}
});
