import test from'node:test';import assert from'node:assert/strict';import{createNativeRelayApi}from'../runtime/native-relay-api.mjs';
const KEY='sk-syntheticCustomerKeyNotOwner000001';
const input=()=>({model:'fixture-model',messages:[{role:'user',content:'fixture'}],max_tokens:32});
const req=(body=input(),key='fixture_idempotency_01')=>new Request('https://apiwild.com/v1/chat/completions',{method:'POST',headers:{authorization:'Bearer '+KEY,'idempotency-key':key,'content-type':'application/json'},body:JSON.stringify(body)});
function fixture(handler){const calls=[];const api=createNativeRelayApi({enabled:true,allowedModels:['fixture-model'],fetchImpl:async(url,init)=>{calls.push({url,init});return handler?handler(url,init):Response.json({id:'fixture',model:'fixture-model',choices:[{message:{role:'assistant',content:'answer'},finish_reason:'stop'}],usage:{prompt_tokens:8,completion_tokens:4}});}});return{api,calls};}
test('customer bearer reaches only Subrouter once; replay returns cached result without duplicate native charge',async()=>{const f=fixture();const r=await f.api.handle(req());assert.equal(r.status,200);assert.equal(f.calls[0].url,'https://subrouter.ai/v1/chat/completions');assert.equal(f.calls[0].init.headers.authorization,'Bearer '+KEY);assert.equal(f.calls[0].init.redirect,'error');assert.equal((await r.json()).usage.total_tokens,12);assert.equal((await f.api.handle(req())).status,200);assert.equal(f.calls.length,1);assert.equal((await f.api.handle(req({...input(),messages:[{role:'user',content:'changed'}]}))).status,409);});
test('unlisted model, tools, streaming, secret in prompt and output bounds reject without spend',async()=>{for(const patch of[{model:'other'},{tools:[]},{stream:true},{max_tokens:4097},{messages:[{role:'user',content:KEY}]}]){const f=fixture();assert.equal((await f.api.handle(req({...input(),...patch}))).status,400);assert.equal(f.calls.length,0);}});
test('network uncertainty never retries and subsequent identical request remains held',async()=>{const f=fixture(()=>{throw Error(KEY);});const r=await f.api.handle(req());assert.equal(r.status,503);assert.ok(!(await r.text()).includes(KEY));assert.equal((await f.api.handle(req())).status,503);assert.equal(f.calls.length,1);});
test('missing/mismatched identity, token echo and unknown usage remain held',async()=>{for(const patch of[{model:'other'},{model:undefined},{usage:{}},{choices:[{message:{role:'assistant',content:KEY}}]}]){const f=fixture(()=>Response.json({id:'fixture',model:'fixture-model',choices:[{message:{role:'assistant',content:'answer'}}],usage:{prompt_tokens:8,completion_tokens:4},...patch}));assert.equal((await f.api.handle(req())).status,503);assert.equal(f.calls.length,1);}});
test('native insufficient balance remains upstream 402 and is not credited locally',async()=>{const f=fixture(()=>new Response('secret upstream message',{status:402}));const r=await f.api.handle(req());assert.equal(r.status,402);const data=await r.json();assert.equal(data.automaticRetry,false);assert.equal(f.calls.length,1);});
test('disabled relay never invokes a provider',async()=>{const api=createNativeRelayApi({fetchImpl:()=>{throw Error();}});assert.equal((await api.handle(req())).status,503);});
