import test from 'node:test';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {createOwnedBillingFromEnv} from '../runtime/owned-billing.mjs';
const env={OWN_BILLING_ENABLED:'true',APIWILD_CHECKOUT_ENABLED:'true',BILLING_MODE:'test',SUPABASE_SECRET_KEY:'sb_secret_abcdefghijklmnop',STRIPE_SECRET_KEY:'rk_test_abcdefghijklmnop',STRIPE_WEBHOOK_SECRET:'whsec_abcdefghijklmnop',STRIPE_CREDIT_PRICE_ID:'price_demo'};
async function run(port,path,method='GET',body,headers={}){const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]);Object.assign(req,{url:path,method,headers:{authorization:'Bearer '+ 'x'.repeat(30),origin:'https://apiwild.com','content-type':'application/json',...headers}});let result;const res={writeHead(status){this.status=status},end(text){result={status:this.status,data:JSON.parse(text)}}};await port.handle(req,res);return result}
function setup({confirmed=true,authStatus=200,suspended=false,checkoutFlag='true',withStripeKey=true}={}){const calls=[];const stripeCalls=[];const fetchImpl=async(url,o)=>{calls.push(url);if(url.endsWith('/auth/v1/user')&&authStatus!==200)return Response.json({error:'expired'},{status:authStatus});return Response.json(url.endsWith('/auth/v1/user')?{id:'12345678-1234-4123-8123-123456789abc',email_confirmed_at:confirmed?'now':null}:url.endsWith('apiwild_gateway_account_initialize')?{initialized:true,customer_id:'12345678-1234-4123-8123-123456789abc',billing_mode:'test'}:url.endsWith('apiwild_billing_read')?{balanceCents:0,orders:[],suspended}:url.endsWith('apiwild_stripe_customer')?{customerId:'cus_demo'}:{registered:true,...{order_id:JSON.parse(o.body).p_order_id,session_id:JSON.parse(o.body).p_session_id}})};const stripeClient={accounts:{retrieve:async()=>({id:'acct_1UCiHk0SGcPsf6AA'})},prices:{retrieve:async()=>({id:'price_demo',active:true,livemode:false,currency:'usd',type:'one_time',unit_amount:100})},checkout:{sessions:{create:async p=>(stripeCalls.push(p),{id:'cs_test_example',mode:'payment',livemode:false,customer:p.customer,client_reference_id:p.client_reference_id,metadata:p.metadata,currency:'usd',amount_subtotal:3000,amount_total:3000,status:'open',payment_status:'unpaid',total_details:{amount_discount:0,amount_tax:0},url:'https://checkout.stripe.com/c/pay/example'})}}};return {calls,stripeCalls,port:createOwnedBillingFromEnv({...env,APIWILD_CHECKOUT_ENABLED:checkoutFlag,STRIPE_SECRET_KEY:withStripeKey?env.STRIPE_SECRET_KEY:undefined},{fetchImpl,stripeClient})}}
test('missing credentials stays disabled',async()=>{const p=await createOwnedBillingFromEnv({});assert.equal((await run(p,'/api/billing')).status,503)});
test('confirmed Supabase identity reads owned ledger',async()=>{const f=setup();const r=await run(await f.port,'/api/billing');assert.equal(r.status,200);assert.equal(r.data.balanceCents,0);assert.equal(r.data.minimumTopupCents,3000)});
test('unconfirmed user cannot read finances',async()=>{const f=setup({confirmed:false});assert.equal((await run(await f.port,'/api/billing')).status,401);assert.equal(f.calls.length,1)});
test('cross-origin checkout blocked before remote auth',async()=>{const f=setup();assert.equal((await run(await f.port,'/api/billing/checkout','POST',{}, {origin:'https://evil.example'})).status,403);assert.equal(f.calls.length,0)});
test('authenticated checkout registers owner and returns Stripe URL without credits',async()=>{const f=setup();const r=await run(await f.port,'/api/billing/checkout','POST',{amountCents:3000,requestId:'12345678-1234-4123-8123-123456789abc'});assert.equal(r.status,200);assert.equal(r.data.creditsGranted,false);assert.ok(r.data.url.startsWith('https://checkout.stripe.com/c/'))});
test('reconcile reads recorded ledger only and never grants credits',async()=>{const f=setup();const r=await run(await f.port,'/api/billing/reconcile?sessionId=cs_test_example');assert.equal(r.status,200);assert.ok(f.calls.every(u=>!u.includes('stripe.com')))});

test('expired auth response returns401 without financial calls',async()=>{const f=setup({authStatus:401});assert.equal((await run(await f.port,'/api/billing')).status,401);assert.equal(f.calls.length,1)});
test('suspended customer may read balance but cannot checkout',async()=>{const f=setup({suspended:true});const p=await f.port;assert.equal((await run(p,'/api/billing')).data.checkoutEnabled,false);assert.equal((await run(p,'/api/billing/checkout','POST',{amountCents:3000,requestId:'12345678-1234-4123-8123-123456789abc'})).status,403)});

for(const checkoutFlag of [undefined,'false','TRUE','1'])test(`configured credentials keep sales closed for flag ${checkoutFlag}`,async()=>{
 const f=setup({checkoutFlag:checkoutFlag??null});const p=await f.port;
 assert.equal((await run(p,'/api/billing')).data.checkoutEnabled,false);
 assert.equal((await run(p,'/api/billing/checkout','POST',{amountCents:3000,requestId:'12345678-1234-4123-8123-123456789abc'})).status,503);
 assert.equal(f.stripeCalls.length,0);assert.ok(f.calls.every(u=>!u.endsWith('apiwild_stripe_customer')&&!u.endsWith('apiwild_stripe_register_checkout')));
});
test('sales switch cannot bypass missing credentials',async()=>{const f=setup({withStripeKey:false});const p=await f.port;assert.equal((await run(p,'/api/billing')).data.checkoutEnabled,false);assert.equal((await run(p,'/api/billing/checkout','POST',{})).status,503);assert.equal(f.stripeCalls.length,0)});
test('configured webhook still verifies signatures with sales disabled',async()=>{
 const f=setup({checkoutFlag:'false'});const p=await f.port;
 const req=Readable.from([Buffer.from('{}')]);Object.assign(req,{url:'/api/billing/webhook',method:'POST',headers:{},rawHeaders:['content-type','application/json','stripe-signature','invalid'],complete:true});
 let result;const res={once(){},writeHead(status){this.status=status},end(body){result={status:this.status,data:JSON.parse(body)}}};
 await p.handle(req,res);assert.equal(result.status,400);assert.equal(result.data.received,false);assert.equal(f.calls.length,0);assert.equal(f.stripeCalls.length,0);
});
