import test from 'node:test';import assert from 'node:assert/strict';
import {createOwnStripeCheckout} from '../runtime/stripe-checkout.mjs';
const owner='test:supabase:12345678-1234-4123-8123-123456789abc',input={amountCents:3000,requestId:'12345678-1234-4123-8123-123456789abc'};
function fixture({price={},session={},registration=false}={}){const calls=[];const stripe={accounts:{retrieve:async()=>({id:'acct_1UCiHk0SGcPsf6AA'})},prices:{retrieve:async()=>({id:'price_test',active:true,livemode:false,currency:'usd',type:'one_time',unit_amount:100,...price})},checkout:{sessions:{create:async(p,o)=>{calls.push({p,o});return {id:'cs_test_example',mode:'payment',livemode:false,customer:p.customer,client_reference_id:p.client_reference_id,metadata:p.metadata,currency:'usd',amount_subtotal:3000,amount_total:3000,status:'open',payment_status:'unpaid',total_details:{amount_discount:0,amount_tax:0},url:'https://checkout.stripe.com/c/pay/example',...session}}}}};return {calls,port:createOwnStripeCheckout({enabled:true,billingMode:'test',accountId:'acct_1UCiHk0SGcPsf6AA',priceId:'price_test',stripeClient:stripe,resolveCustomer:async()=> 'cus_test',register:async(n,p)=>{calls.push({n,p});if(registration)throw Error('private');return {registered:true,order_id:p.p_order_id,session_id:p.p_session_id}}})};}
test('disabled does not create checkout',async()=>{await assert.rejects(createOwnStripeCheckout().checkout(owner,input),{code:'checkout_disabled'})});
test('minimum, whole-dollar units, caller identity and unexpected fields rejected before write',async()=>{for(const [o,i] of [[owner,{...input,amountCents:2900}],[owner,{...input,amountCents:3001}],['live:'+owner,input],[owner,{...input,userId:owner}]]){const f=fixture();await assert.rejects(f.port.checkout(o,i));assert.equal(f.calls.length,0)}});
test('registers canonical unpaid session before returning and never grants credits',async()=>{const f=fixture();const r=await f.port.checkout(owner,input);assert.equal(r.creditsGranted,false);assert.equal(f.calls.length,2);assert.equal(f.calls[0].p.line_items[0].quantity,30);assert.equal(f.calls[0].p.payment_method_types,undefined);assert.deepEqual(f.calls[0].p.adaptive_pricing,{enabled:false});assert.equal(f.calls[0].p.branding_settings.display_name,'API WILD');assert.equal(f.calls[0].p.payment_intent_data.metadata.order_id,r.orderId);assert.equal(f.calls[1].p.p_order_id,r.orderId)});
test('same owner/request gets same Stripe idempotency key; another owner is isolated',async()=>{const f=fixture();await f.port.checkout(owner,input);await f.port.checkout(owner,input);assert.equal(f.calls[0].o.idempotencyKey,f.calls[2].o.idempotencyKey);await f.port.checkout(owner.replace('789abc','789abd'),input);assert.notEqual(f.calls[0].o.idempotencyKey,f.calls[4].o.idempotencyKey)});
test('unregistered checkout URL is never returned; no automatic retry',async()=>{const f=fixture({registration:true});await assert.rejects(f.port.checkout(owner,input),{code:'checkout_unavailable'});assert.equal(f.calls.length,2)});
test('wrong price or session totals fail closed',async()=>{for(const overrides of [{price:{unit_amount:99}},{session:{amount_total:2999}},{session:{customer:'cus_other'}},{session:{url:'https://evil.example/c/pay'}}]){const f=fixture(overrides);await assert.rejects(f.port.checkout(owner,input));assert.ok(!f.calls.some(x=>x.n))}});
