import test from 'node:test';import assert from 'node:assert/strict';
import {createNativeCustomerReader,NATIVE_STATION_ORIGIN} from '../runtime/subrouter-native-customer.mjs';
const config={enabled:true,stationOrigin:NATIVE_STATION_ORIGIN,userId:42,sessionCookie:'station-session=fixture-only'};
function fixture(self={id:42,quota:500000},data=[]){const calls=[];return {calls,reader:createNativeCustomerReader({...config,fetchImpl:async(url,options)=>{calls.push({url,options});return Response.json({success:true,data:url.endsWith('/user/self')?self:data});}})}}
test('default disabled has no network or native activation',async()=>{const r=createNativeCustomerReader({fetchImpl:()=>assert.fail()});await assert.rejects(r.read('account'),{code:'native_customer_disabled'});});
test('station host, identity and cookie must be explicit and valid',()=>{for(const bad of [{stationOrigin:'https://example.test'},{userId:0},{sessionCookie:'secret\r\ninjected'}])assert.throws(()=>createNativeCustomerReader({...config,...bad}),{code:'native_invalid_configuration'});});
test('native account is checked with cookie and New-Api-User and quota stays native',async()=>{const f=fixture();const r=await f.reader.read('account');assert.equal(r.account.quota,500000);assert.equal(r.quotaUnitsPerUsd,500000);assert.equal(f.calls[0].url,NATIVE_STATION_ORIGIN+'/api/dist/user/self');assert.equal(f.calls[0].options.headers['New-Api-User'],'42');assert.equal(f.calls[0].options.redirect,'error');assert.equal(f.calls[0].options.headers.Authorization,undefined);});
test('wrong native identity prevents later key or log fetch',async()=>{const f=fixture({id:99});await assert.rejects(f.reader.read('keys'),{code:'native_owner_mismatch'});assert.equal(f.calls.length,1);});
test('key listing drops upstream raw secrets and no writes are available',async()=>{const f=fixture({id:42},[{id:1,name:'project',key:'sk-secret',access_token:'private',remain_quota:100}]);const r=await f.reader.read('keys');assert.deepEqual(r,[{id:1,name:'project',remain_quota:100}]);await assert.rejects(f.reader.read('createKey'),{code:'native_operation_not_allowed'});assert.equal(f.calls.length,2);assert.ok(f.calls.every(c=>c.options.method==='GET'));});
test('fixed model/log routes reject arbitrary URL operations before fetch',async()=>{const f=fixture({id:42},{items:[],total:0});await f.reader.read('models');await f.reader.read('logs');assert.ok(f.calls.some(c=>c.url.endsWith('/api/dist/site/models')));assert.ok(f.calls.some(c=>c.url.endsWith('/api/dist/user/logs?p=1&page_size=20')));const before=f.calls.length;await assert.rejects(f.reader.read('https://evil.test'),{code:'native_operation_not_allowed'});assert.equal(f.calls.length,before);});
test('failures never echo credential or upstream error text',async()=>{const r=createNativeCustomerReader({...config,fetchImpl:async()=>Response.json({success:false,message:'station-session=fixture-only'})});await assert.rejects(r.read('account'),e=>e.code==='native_request_failed'&&!e.message.includes('fixture-only'));});
test('oversized receipts remain bounded and sanitized',async()=>{const r=createNativeCustomerReader({...config,fetchImpl:async()=>new Response('{}',{headers:{'content-type':'application/json','content-length':'524289'}})});await assert.rejects(r.read('account'),{code:'native_response_too_large'});});

test('log projection excludes customer content, IP and untrusted provider extras',async()=>{const f=fixture({id:42},{items:[{id:1,model_name:'exact',quota:5,content:'private prompt',ip:'private address',other:{key:'secret'}}],total:1});const r=await f.reader.read('logs');assert.deepEqual(r.items,[{id:1,model_name:'exact',quota:5}]);});

test('key fields cannot smuggle nested credentials through presentation projection',async()=>{const f=fixture({id:42},[{id:1,name:{secret:'private'},used_quota:7}]);assert.deepEqual(await f.reader.read('keys'),[{id:1,used_quota:7}]);});
