import test from 'node:test';import assert from 'node:assert/strict';
import {createNativeBilling} from '../runtime/subrouter-native-billing.mjs';
import {NATIVE_STATION_ORIGIN} from '../runtime/subrouter-native-customer.mjs';
const config={enabled:true,nativeCheckoutEnabled:true,stationOrigin:NATIVE_STATION_ORIGIN,userId:42,sessionCookie:'fixture-session=private'};
const topup={currency:'USD',exchange_rate:1,enable_stripe_topup:true,stripe_min_topup:5,pay_methods:[{type:'stripe'}]};
function fixture({self={id:42},info=topup,link='https://checkout.stripe.com/c/pay/fixture',history={items:[]}}={}){
 const calls=[];return {calls,port:createNativeBilling({...config,fetchImpl:async(url,options)=>{
  calls.push({url,options});return Response.json(url.endsWith('/user/self')?{success:true,data:self}:url.endsWith('/topup/info')?{success:true,data:info}:url.includes('/topup/history')?{success:true,data:history}:{message:'success',data:{pay_link:link,secret:'hidden'}});
 }})};
}
test('disabled billing and checkout never call upstream',async()=>{const port=createNativeBilling({fetchImpl:()=>assert.fail()});await assert.rejects(port.read('info'),{code:'native_billing_disabled'});await assert.rejects(port.checkout({amountCents:3000,currency:'USD'}),{code:'native_checkout_disabled'});});
test('checkout defaults disabled even when native account reading is enabled',async()=>{const port=createNativeBilling({...config,nativeCheckoutEnabled:undefined,fetchImpl:()=>assert.fail()});await assert.rejects(port.checkout({amountCents:3000,currency:'USD'}),{code:'native_checkout_disabled'});});
test('checkout verifies same native owner and returns URL without granting credits',async()=>{const f=fixture();const result=await f.port.checkout({amountCents:3000,currency:'USD'});assert.deepEqual(result,{authority:'subrouter-native-station',url:'https://checkout.stripe.com/c/pay/fixture',creditsGranted:false});assert.equal(f.calls.length,3);const call=f.calls[2];assert.equal(call.url,NATIVE_STATION_ORIGIN+'/api/dist/topup/stripe/pay');assert.equal(call.options.headers['New-Api-User'],'42');assert.equal(call.options.headers.cookie,config.sessionCookie);assert.equal(call.options.redirect,'error');assert.deepEqual(JSON.parse(call.options.body),{amount:30,payment_method:'stripe',currency:'USD',return_url:'https://apiwild.com/api-account/billing?payment=return'});});
test('owner mismatch prevents any checkout or info request',async()=>{const f=fixture({self:{id:43}});await assert.rejects(f.port.checkout({amountCents:3000,currency:'USD'}),{code:'native_owner_mismatch'});assert.equal(f.calls.length,1);});
test('unconfigured Stripe, unsupported currencies and FX never create checkout',async()=>{for(const delta of [{currency:'CNY'},{exchange_rate:7},{enable_stripe_topup:false},{pay_methods:[]},{stripe_min_topup:50}]){const f=fixture({info:{...topup,...delta}});await assert.rejects(f.port.checkout({amountCents:3000,currency:'USD'}),{code:'native_checkout_not_configured'});assert.equal(f.calls.length,2);}});
test('browser cannot supply owner, destination, payment method, tiers or fractional cents',async()=>{for(const input of [{amountCents:3000.1,currency:'USD'},{amountCents:0,currency:'USD'},{amountCents:25001,currency:'USD'},{amountCents:3000,currency:'CNY'},...['userId','return_url','payment_method','tier_index'].map(key=>({amountCents:3000,currency:'USD',[key]:'injected'}))]){const f=fixture();await assert.rejects(f.port.checkout(input),{code:'native_billing_invalid_request'});assert.equal(f.calls.length,0);}});
test('Stripe checkout redirects are restricted to exact verified host',async()=>{for(const link of ['http://checkout.stripe.com/c/pay/x','https://checkout.stripe.com.evil.test/c/pay/x','https://x@checkout.stripe.com/c/pay/x','https://checkout.stripe.com/evil','javascript:alert(1)']){const f=fixture({link});await assert.rejects(f.port.checkout({amountCents:3000,currency:'USD'}),{code:'native_checkout_receipt_unavailable'});}});
test('native history is projected without customer identity or server secrets',async()=>{const f=fixture({history:{items:[{id:1,trade_no:'order',amount:10,status:'success',customer_email:'private',stripe_secret:'private',user_id:42,nested:{secret:'private'}}]}});assert.deepEqual(await f.port.read('history'),{authority:'subrouter-native-station',items:[{id:1,trade_no:'order',amount:10,status:'success'}],creditsGranted:false});assert.ok(f.calls.every(call=>call.options.method==='GET'));});
test('info reports availability without projecting arbitrary payment settings',async()=>{const f=fixture({info:{...topup,stripe_secret:'private',amount_tiers:[{amount:10,bonus:0,secret:'private'}]}});const result=await f.port.read('info');assert.equal(result.checkoutEnabled,true);assert.deepEqual(result.amountTiers,[{amount:10,bonus:0}]);assert.equal(JSON.stringify(result).includes('private'),false);});
test('POST failure is sanitized and never silently retried',async()=>{let writes=0;const port=createNativeBilling({...config,fetchImpl:async(url,options)=>{if(options.method==='POST'){writes++;throw Error('ambiguous private response');}return Response.json({success:true,data:url.endsWith('/user/self')?{id:42}:topup});}});await assert.rejects(port.checkout({amountCents:3000,currency:'USD'}),{code:'native_billing_unavailable'});assert.equal(writes,1);});
test('hung transport is bounded and does not become a duplicate checkout retry',async()=>{let calls=0;const port=createNativeBilling({...config,timeoutMs:5,fetchImpl:()=>{calls++;return new Promise(()=>{});}});await assert.rejects(port.read('info'),{code:'native_billing_timeout'});assert.equal(calls,1);});
test('oversized or invalid native responses fail closed',async()=>{for(const response of [new Response('{}',{headers:{'content-type':'application/json','content-length':'65537'}}),Response.json({success:false,message:'success',data:{id:42}}),Response.json({success:true,data:{id:42}},{status:401})]){const port=createNativeBilling({...config,fetchImpl:async()=>response});await assert.rejects(port.read('info'));}});

test('owner policy rejects $29 before any transport and accepts exactly $30',async()=>{const denied=fixture();await assert.rejects(denied.port.checkout({amountCents:2900,currency:'USD'}),{code:'native_billing_invalid_request'});assert.equal(denied.calls.length,0);const accepted=fixture();await accepted.port.checkout({amountCents:3000,currency:'USD'});assert.equal(JSON.parse(accepted.calls.at(-1).options.body).amount,30);assert.equal((await accepted.port.read('info')).minimumTopupUsd,30);});

test('missing or impossible native minimum never advertises checkout availability',async()=>{for(const minimum of [undefined,null,0,-1,'30',Infinity,251]){const f=fixture({info:{...topup,stripe_min_topup:minimum}});assert.equal((await f.port.read('info')).checkoutEnabled,false);await assert.rejects(f.port.checkout({amountCents:3000,currency:'USD'}),{code:'native_checkout_not_configured'});assert.ok(f.calls.every(call=>call.options.method==='GET'));}});
