import test from 'node:test';import assert from 'node:assert/strict';import {createNativeAuth} from '../runtime/subrouter-native-auth.mjs';
const base='https://apiwild.com',station='https://apiwild.subrouter.ai';
const payload={username:'customer',password:'fixture-password',acceptedTerms:true};
function request(op,body=payload,cookie){return new Request(base+'/api/native/auth/'+op,{method:op==='self'?'GET':'POST',headers:{origin:base,'content-type':'application/json',...(cookie?{cookie}:{})},body:op==='self'?undefined:JSON.stringify(body)});}
function fixture(handler){const records=new Map(),calls=[];const store={get:async k=>records.get(k),put:async(k,v)=>records.set(k,v),delete:async k=>records.delete(k)};const auth=createNativeAuth({enabled:true,stationOrigin:station,customerOrigin:base,sessionStore:store,fetchImpl:async(url,opts)=>{calls.push({url,opts});if(handler){const r=await handler(url,opts);if(r)return r;}return Response.json({success:true,data:url.endsWith('/login')||url.endsWith('/self')?{id:42,username:'customer',quota:500000}:null},{headers:url.endsWith('/login')?{'set-cookie':'native-session=upstream-private; Path=/; HttpOnly; Secure'}:{}});}});return {auth,calls,records};}
test('default auth is unavailable and does not invoke dependencies',async()=>{const response=await createNativeAuth({}).handle(request('login'));assert.equal(response.status,503);});
test('login verifies native identity and exposes only a secure opaque local handle',async()=>{const f=fixture();const response=await f.auth.handle(request('login'));assert.equal(response.status,200);const cookie=response.headers.get('set-cookie');assert.match(cookie,/^__Host-apiwild_native=[a-f0-9]{64}; Path=\/; Secure; HttpOnly; SameSite=Strict/);assert.ok(!cookie.includes('upstream-private'));assert.ok(!(await response.text()).includes('upstream-private'));assert.equal(f.records.size,1);assert.ok(![...f.records.keys()][0].includes(cookie.split('=',2)[1].slice(0,64)));assert.equal(f.calls[1].opts.headers.cookie,'native-session=upstream-private');assert.equal(f.calls[1].opts.headers['New-Api-User'],'42');assert.equal(f.calls[0].opts.redirect,'error');});
test('registration uses exact native fields and does not synthesize a session',async()=>{const f=fixture();const r=await f.auth.handle(request('register',{...payload,email:'a@example.test',verification_code:'123',aff_code:'affiliate'}));assert.equal(r.status,200);assert.deepEqual(await r.json(),{success:true,needsLogin:true});assert.equal(r.headers.get('set-cookie'),null);assert.equal(f.records.size,0);assert.equal(JSON.parse(f.calls[0].opts.body).acceptedTerms,undefined);});
test('cross-origin and unaccepted legal consent reject before upstream',async()=>{const f=fixture();const r=request('login');const evil=new Request(r,{headers:{origin:'https://evil.test','content-type':'application/json'}});assert.equal((await f.auth.handle(evil)).status,403);assert.equal((await f.auth.handle(request('login',{...payload,acceptedTerms:false}))).status,400);assert.equal(f.calls.length,0);});
test('missing native cookie or mismatched self cannot grant API WILD session',async()=>{for(const bad of ['cookie','identity']){const f=fixture(url=>url.endsWith('/login')&&bad==='cookie'?Response.json({success:true,data:{id:42}}):url.endsWith('/self')&&bad==='identity'?Response.json({success:true,data:{id:99}}):null);assert.ok((await f.auth.handle(request('login'))).status>=400);assert.equal(f.records.size,0);}});
test('self and logout use server record and clear local session even if native logout fails',async()=>{const f=fixture(url=>url.endsWith('/logout')?new Response('',{status:503}):null);const login=await f.auth.handle(request('login'));const cookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await f.auth.handle(request('self',undefined,cookie))).status,200);const out=await f.auth.handle(request('logout',{},cookie));assert.equal(out.status,200);assert.match(out.headers.get('set-cookie'),/Max-Age=0/);assert.equal(f.records.size,0);assert.equal((await f.auth.handle(request('self',undefined,cookie))).status,401);});
test('upstream rejection does not echo credentials or arbitrary error content',async()=>{const f=fixture(()=>Response.json({success:false,message:'fixture-password upstream-private'}));const r=await f.auth.handle(request('login'));assert.equal(r.status,400);assert.ok(!(await r.text()).includes('fixture-password'));});
test('duplicate opaque cookies are not accepted as authenticated identity',async()=>{const f=fixture();const l=await f.auth.handle(request('login'));const cookie=l.headers.get('set-cookie').split(';')[0];assert.equal((await f.auth.handle(request('self',undefined,cookie+'; '+cookie))).status,401);});
test('login body stall has a finite ingress deadline',async t=>{t.mock.timers.enable({apis:['setTimeout']});const f=fixture();const r=new Request(base+'/api/native/auth/login',{method:'POST',duplex:'half',headers:{origin:base,'content-type':'application/json'},body:new ReadableStream({pull(){return new Promise(()=>{});}})});const pending=f.auth.handle(r);t.mock.timers.tick(5000);assert.equal((await pending).status,408);assert.equal(f.calls.length,0);});

test('opaque session drives native account read without returning upstream cookie',async()=>{const f=fixture();const l=await f.auth.handle(request('login'));const cookie=l.headers.get('set-cookie').split(';')[0];const r=await f.auth.readCustomer(request('self',undefined,cookie),'account');assert.equal(r.account.id,42);assert.ok(!JSON.stringify(r).includes('upstream-private'));});
