// Personal-workspace API; no shared members or invitations are fabricated.
import {strictObject} from './supabase-gateway-rpc.mjs';
const capabilities=['chat','code','research','voice','transcribe','speak'];
export function createWorkspacePolicy({verifyOwner,rpc}){
 if(typeof verifyOwner!=='function'||typeof rpc!=='function')throw Error('workspace_invalid_configuration');
 function receipt(value,owner){strictObject(value,['workspaceType','members','roles','capabilities','dailyLimitUsdMicros','sharedMembershipEnabled']);if(value.workspaceType!=='personal'||value.sharedMembershipEnabled!==false||!Array.isArray(value.members)||value.members.length!==1||value.members[0]?.customerId!==owner.split(':')[2]||value.members[0]?.role!=='owner'||!Array.isArray(value.roles)||value.roles.length!==1||value.roles[0]?.name!=='owner'||!Array.isArray(value.roles[0]?.permissions)||value.roles[0].permissions.length!==4||value.roles[0].permissions.some(p=>!['manage_keys','manage_billing','manage_guardrails','view_usage'].includes(p))||!Array.isArray(value.capabilities)||value.capabilities.some(c=>!capabilities.includes(c))||!Number.isSafeInteger(value.dailyLimitUsdMicros)||value.dailyLimitUsdMicros<0||value.dailyLimitUsdMicros>1000000000000)throw Error('workspace_invalid_response');strictObject(value.members[0],['customerId','role']);strictObject(value.roles[0],['name','permissions']);return value}
 async function owner(authorization){const v=await verifyOwner({authorization});if(!v||!['live','test'].includes(v.billingMode)||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(v.customerId))throw Error('workspace_unauthorized');return v.billingMode+':supabase:'+v.customerId}
 return Object.freeze({async read(authorization){const p_owner=await owner(authorization);return receipt(await rpc('apiwild_workspace_policy',{p_owner,p_capabilities:null,p_daily_limit:null}),p_owner)},async update(authorization,input){strictObject(input,['capabilities','dailyLimitUsdMicros']);if(!Array.isArray(input.capabilities)||input.capabilities.length>6||new Set(input.capabilities).size!==input.capabilities.length||input.capabilities.some(c=>!capabilities.includes(c))||!Number.isSafeInteger(input.dailyLimitUsdMicros)||input.dailyLimitUsdMicros<0||input.dailyLimitUsdMicros>1000000000000)throw Error('workspace_invalid_policy');const p_owner=await owner(authorization);return receipt(await rpc('apiwild_workspace_policy',{p_owner,p_capabilities:[...input.capabilities],p_daily_limit:input.dailyLimitUsdMicros}),p_owner)}});
}
