import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import{scan,acquireLock}from'../scripts/maintenance/controller.mjs';import{observation}from'../scripts/maintenance/policy.mjs';
const sha='a'.repeat(40),other='b'.repeat(40),config={repoPath:'fixture',site:'https://apiwild.com'};
function fixture(){let at=1000000,commit=sha,ciFailure=false,unavailable=false,deployed=sha,deepCalls=0;
 return{set(v){({at=at,commit=commit,ciFailure=ciFailure,unavailable=unavailable,deployed=deployed}=v);},calls:()=>deepCalls,
 deps:{now:()=>at,gitOp:async(_,args)=>args[0]==='rev-parse'?commit:args[0]==='ls-tree'?'package.json':args[0]==='show'?'{}':'',githubOp:async()=>{deepCalls++;return JSON.stringify([{headSha:commit,workflowName:'API WILD checks',status:'completed',conclusion:ciFailure?'failure':'success'}]);},run:async()=>({code:0,stdout:''}),request:async()=>{if(unavailable)throw Error('timeout');return Response.json({authority:'apiwild-owned-runtime',deploymentCommit:deployed});}}};}
test('real site outage reaches confirmed incident without requiring a config response',async()=>{const f=fixture(),state={};f.set({unavailable:true});const a=await scan(config,state,f.deps),b=await scan(config,state,f.deps);assert.ok(a.failures.includes('Public runtime configuration unavailable'));assert.equal(observation(observation(null,a,1),b,2).action,'confirmed_failure');});
test('hourly CI failure is preserved for confirmation on the next five minute tick',async()=>{const f=fixture(),state={};f.set({ciFailure:true});const a=await scan(config,state,f.deps);f.set({at:1300000});const b=await scan(config,state,f.deps);assert.equal(f.calls(),1);assert.deepEqual(b.failures,a.failures);assert.equal(observation(observation(null,a,1),b,2).action,'confirmed_failure');f.set({commit:other,deployed:other,ciFailure:false});assert.deepEqual((await scan(config,state,f.deps)).failures,[]);assert.equal(f.calls(),2);});
test('deployment grace is bounded and clears when the exact new commit is live',async()=>{const f=fixture(),state={};f.set({deployed:other});assert.deepEqual((await scan(config,state,f.deps)).failures,[]);f.set({at:2800001});assert.ok((await scan(config,state,f.deps)).failures.includes('Deployment commit mismatch'));f.set({deployed:sha});assert.deepEqual((await scan(config,state,f.deps)).failures,[]);assert.equal(state.pendingCommit,null);});
test('overlapping ticks cannot both acquire a recovered process lease',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'apiwild-lease-')),file=path.join(dir,'lease.json');try{await fs.writeFile(file,JSON.stringify({pid:2147483000}));const results=await Promise.all([acquireLock(file),acquireLock(file)]);assert.equal(results.filter(Boolean).length,1);assert.equal(JSON.parse(await fs.readFile(file)).pid,process.pid);assert.equal(await acquireLock(file),false);}finally{await fs.unlink(file).catch(()=>{});await fs.unlink(file+'.recovery').catch(()=>{});await fs.rmdir(dir);}});
test('Git read failure is an operational blocker rather than a fabricated malformed JSON incident',async()=>{const f=fixture(),original=f.deps.gitOp;f.deps.gitOp=async(root,args)=>{if(args[0]==='show')throw Error('bounded read failed');return original(root,args);};await assert.rejects(scan(config,{},f.deps),/bounded read failed/);});
