import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './lifecycle.test.mjs';
const sku='omegatv-premium-1c-1m';
function fixture(){const a=setup({STRIPE_SECRET_KEY:'rk_live_fixture',STRIPE_WEBHOOK_SECRET:'whsec_fixture',STOREFRONT_CHECKOUT_ENABLED:'true',WEBHOOK_INGRESS_VERIFIED:'true'});a.setResponder(url=>url.endsWith('/account')?Response.json({id:'acct_1UCiHN194XZKj6cF',charges_enabled:true}):null);a.setSession({id:'cs_live_fixture',url:'https://checkout.stripe.com/c/pay/fixture',status:'open'});return a;}
function request(body,origin='https://omegatv.ca'){return new Request('https://apiwild.com/api/storefront/checkout',{method:'POST',headers:{origin,'content-type':'application/json','cf-connecting-ip':'192.0.2.1'},body:JSON.stringify(body)});}
test('storefront selects server price, brand and CAD; no auto renewals, dynamic methods',async()=>{const a=fixture(),route=a.load('app/api/storefront/checkout/route.ts');const input={sku,requestId:crypto.randomUUID(),amount:1,price:'fake'};assert.equal((await route.POST(request(input))).status,200);const p=a.calls.find(c=>c.url.endsWith('/checkout/sessions')).opts.body;assert.equal(p.get('mode'),'payment');assert.equal(p.get('branding_settings[display_name]'),'Omega TV');assert.equal(p.get('adaptive_pricing[enabled]'),'false');assert.equal(p.get('payment_method_types[0]'),null);assert.notEqual(p.get('line_items[0][price]'),'fake');assert.equal(p.get('success_url'),'https://omegatv.ca/?checkout=success&order_id=store_'+input.requestId);assert.equal(a.sql.prepare('SELECT amount_cents FROM storefront_orders').get().amount_cents,1500);assert.equal((await route.POST(request(input))).status,200);assert.equal(a.calls.filter(c=>c.url.endsWith('/checkout/sessions')).length,1);});
test('storefront rejects wrong origins, unknown selections, wrong account and disabled payments',async()=>{const a=fixture(),r=a.load('app/api/storefront/checkout/route.ts'),body={sku,requestId:crypto.randomUUID()};assert.equal((await r.POST(request(body,'https://evil.example'))).status,403);assert.equal((await r.POST(request({...body,sku:'legacytv-premium-1c-1m'}))).status,400);a.setResponder(url=>url.endsWith('/account')?Response.json({id:'wrong',charges_enabled:true}):null);assert.equal((await r.POST(request(body))).status,503);a.env.STOREFRONT_CHECKOUT_ENABLED='false';assert.equal((await r.POST(request(body))).status,503);});
test('paid-only manual fulfillment, replay once, mismatches blocked and refund hold retained',async()=>{const a=fixture(),r=a.load('app/api/storefront/checkout/route.ts'),id=crypto.randomUUID();assert.equal((await r.POST(request({sku,requestId:id}))).status,200);const orderId='store_'+id;const session={id:'cs_live_fixture',livemode:true,mode:'payment',client_reference_id:orderId,metadata:{storefront_order_id:orderId,storefront_sku:sku,storefront_brand:'omegatv'},currency:'cad',amount_subtotal:1500,amount_total:1695,total_details:{amount_tax:195,amount_discount:0},status:'complete',payment_status:'unpaid',payment_intent:'pi_fixture'};const event={type:'checkout.session.completed',data:{object:session}};const api=a.load('lib/storefront.ts');a.setSession(session);await api.reconcileStorefrontEvent(event);assert.equal(a.sql.prepare('SELECT COUNT(*) n FROM storefront_fulfillment').get().n,0);a.setSession({...session,payment_status:'paid',amount_subtotal:1});await assert.rejects(()=>api.reconcileStorefrontEvent(event));a.setSession({...session,payment_status:'paid'});await api.reconcileStorefrontEvent(event);await api.reconcileStorefrontEvent({...event,type:'checkout.session.async_payment_succeeded'});assert.equal(a.sql.prepare('SELECT COUNT(*) n FROM storefront_fulfillment').get().n,1);assert.equal(a.sql.prepare('SELECT status FROM storefront_orders').get().status,'paid');a.sql.prepare("UPDATE storefront_orders SET status='refunded'").run();a.sql.prepare("UPDATE storefront_fulfillment SET status='review_required'").run();await api.reconcileStorefrontEvent(event);assert.equal(a.sql.prepare('SELECT status FROM storefront_orders').get().status,'refunded');assert.equal(a.sql.prepare('SELECT status FROM storefront_fulfillment').get().status,'review_required');});
test('storefront database failure does not acknowledge successful fulfillment',async()=>{const a=fixture(),id=crypto.randomUUID();await a.load('app/api/storefront/checkout/route.ts').POST(request({sku,requestId:id}));const s={id:'cs_live_fixture',livemode:true,mode:'payment',client_reference_id:'store_'+id,metadata:{storefront_order_id:'store_'+id,storefront_sku:sku,storefront_brand:'omegatv'},currency:'cad',amount_subtotal:1500,amount_total:1500,total_details:{amount_tax:0},status:'complete',payment_status:'paid',payment_intent:'pi_fixture'};a.setSession(s);a.failBatch(true);await assert.rejects(()=>a.load('lib/storefront.ts').reconcileStorefrontEvent({type:'checkout.session.completed',data:{object:s}}));assert.equal(a.sql.prepare('SELECT COUNT(*) n FROM storefront_fulfillment').get().n,0);});
