'use client';
import {useEffect,useRef,useState} from 'react';
import {verifiedCheckoutUrl} from '@/lib/owned-client-config.mjs';
import {customerApi} from '@/lib/customer-api';
import {CreditPackCards} from '@/app/public-credit-pack-cards';
import {checkoutRequest,clearConfirmedCheckouts,saveCheckoutOrder,saveFailedCheckoutOrder,verifiedCreditOffers,type CreditOffers,type CreditPack} from '@/lib/owned-credit-offers.mjs';
type BillingData={balanceCents:number;orders:Record<string,any>[];checkoutEnabled:boolean;minimumTopupCents:number;creditOffers:CreditOffers};
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100);
export default function Billing(){
 const[data,setData]=useState<BillingData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[amount,setAmount]=useState('30');const lock=useRef(false);
 async function load(){const result=await customerApi('/api/billing');if(!Number.isSafeInteger(result.balanceCents)||!Array.isArray(result.orders)||!Number.isSafeInteger(result.minimumTopupCents)||typeof result.checkoutEnabled!=='boolean')throw Error('Billing information could not be verified.');const creditOffers=verifiedCreditOffers(result.creditOffers);clearConfirmedCheckouts(sessionStorage,result.orders,creditOffers.promotion.id);setData({...result,creditOffers})}
 useEffect(()=>{const params=new URLSearchParams(location.search);if(params.has('session_id')||params.has('payment')||params.has('cancelled'))setNotice('Checkout has returned. Refresh to see the payment status; returning here does not add credits.');load().catch(e=>setError(e.message));},[]);
 async function action(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 const cents=/^\d+$/.test(amount)?Number(amount)*100:NaN,minimum=Math.max(3000,data?.minimumTopupCents??3000),valid=Number.isSafeInteger(cents)&&cents>=minimum&&cents<=100000000;
 async function checkout(pack?:CreditPack){await action(async()=>{if(data?.checkoutEnabled!==true)throw Error('Credit purchases are temporarily unavailable.');if(!pack&&!valid)throw Error('Choose a whole-dollar amount of at least '+money(minimum)+'.');const identity=pack?{packageId:pack.id,promotionId:data.creditOffers.promotion.id}:{amountCents:cents};const request=checkoutRequest(sessionStorage,identity);const result=await customerApi('/api/billing/checkout',{method:'POST',body:JSON.stringify(request.body)}).catch(error=>{saveFailedCheckoutOrder(sessionStorage,request,error);throw error;});if(pack&&result.packageId!==pack.id)throw Error('The selected credit pack could not be confirmed. Your checkout request has been preserved.');const url=verifiedCheckoutUrl(result.url);saveCheckoutOrder(sessionStorage,request,result.orderId);location.assign(url);})}
 return <>{error&&<div className="form-error" role="alert">{error} <button disabled={busy} onClick={()=>action(load)}>Retry</button></div>}{notice&&<p className="billing-notice" role="status">{notice}</p>}{!data&&!error?<p role="status">Loading credits…</p>:data&&<><section className="console-panel"><h2>API WILD credits</h2><strong>{money(data.balanceCents)}</strong><p>Your recorded API WILD balance. Requests and payment reviews may reserve funds before final settlement.</p><button disabled={busy} onClick={()=>action(load)}>Refresh balance and payments</button></section><CreditPackCards offers={data.creditOffers} disabled={busy||!data.checkoutEnabled} onChoose={pack=>void checkout(pack)} onRefresh={()=>void action(load)}/><section className="console-panel"><h2>Custom credit top-up</h2><p>One-time USD credit purchase. Minimum {money(minimum)}, in whole dollars. No recurring subscription.</p><label>Amount (USD)<input type="number" min={minimum/100} max="1000000" step="1" value={amount} disabled={busy||!data.checkoutEnabled} onChange={e=>setAmount(e.target.value)}/></label><button className="pill-button dark" disabled={busy||!valid||!data.checkoutEnabled} onClick={()=>void checkout()}>{busy?'Opening checkout…':data.checkoutEnabled?'Continue to Stripe':'Credit purchases not activated'}</button><p>Custom top-ups add the amount purchased, with no pack bonus. Credits are added only after the server verifies successful payment.</p></section><section className="console-panel"><h2>Payment history</h2>{data.orders.length?data.orders.map((order,index)=><div className="setting-row" key={order.id??order.session_id??index}><strong>{Number.isSafeInteger(order.amount_cents)?money(order.amount_cents):'Amount awaiting confirmation'}</strong><span>{typeof order.status==='string'?order.status.replaceAll('_',' '):'Status awaiting confirmation'}{Number.isSafeInteger(order.credit_cents)&&order.credit_cents>order.amount_cents&&<> · {money(order.credit_cents)} pack total, including {money(order.bonus_cents)} bonus</>}</span></div>):<p>No recorded purchases.</p>}</section></>}</>;
}
