'use client';
import {useEffect,useRef,useState} from 'react';
import {customerApi} from '@/lib/customer-api';
import catalog from '@/app/models/public-models.json';
type Message={role:'user'|'assistant';content:string};
const price=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:6}).format(n);
export default function OwnedPlayground({mode}:{mode:'chat'|'code'|'research'}){
 const[model,setModel]=useState(catalog.models[0].model_name),[input,setInput]=useState(''),[messages,setMessages]=useState<Message[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[usage,setUsage]=useState<{prompt_tokens:number;completion_tokens:number}|null>(null),[availability,setAvailability]=useState<any>(null),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[pending,setPending]=useState<{id:string;body:string}|null>(null);const lock=useRef(false);
 const selected=catalog.models.find(m=>m.model_name===model)!;
 const routes=Array.isArray(availability?.models)?availability.models.filter((r:any)=>r.capability===mode&&catalog.models.some(m=>m.model_name===r.model)&&Number.isSafeInteger(r.maxOutputTokens)&&r.maxOutputTokens>0):[];
 const route=routes.find((r:any)=>r.model===model),ready=availability?.inferenceConfigured===true&&Boolean(route);
 useEffect(()=>{if(messages.length||pending||!routes.length||route)return;setModel(routes[0].model)},[availability,mode]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);customerApi('/api/gateway',{signal:controller.signal}).then(v=>{if(!controller.signal.aborted){setAvailability(v);setError('')}}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[retry]);
 async function send(repeat=false){if(lock.current)return;let request=pending;if(!repeat){if(pending||!input.trim()||!ready)return;const next:Message[]=[...messages,{role:'user',content:input.trim()}];request={id:crypto.randomUUID(),body:JSON.stringify({mode,model,messages:next,max_tokens:Math.min(512,route.maxOutputTokens),stream:false})};setMessages(next);setInput('');setPending(request);}if(!request)return;lock.current=true;setBusy(true);setError('');try{const value=await customerApi('/api/gateway',{method:'POST',headers:{'Idempotency-Key':request.id},body:request.body});if(value.ok!==true||typeof value.result?.text!=='string')throw Error('The response could not be confirmed. Retry the same request to reconcile it.');setMessages(current=>[...current,{role:'assistant',content:value.result.text}]);setUsage(value.result.usage);setPending(null);}catch(e){const failure=e as any;const code=failure.data?.error;const text=failure.status===402?'Your available credit is too low for this request. Add credits, then try again.':failure.status===503?'Inference is not available for this route yet. No working response has been confirmed.':failure.message;setError(text);if([400,401,402,403,404,422,429].includes(failure.status)){setPending(null);}}finally{lock.current=false;setBusy(false)}}
 return <section className="console-panel"><div className="billing-toolbar"><h2>{mode==='code'?'Coding':mode==='research'?'Research':'Chat'} playground</h2><button disabled={busy||loading} onClick={()=>setRetry(v=>v+1)}>Refresh availability</button></div><p>{mode==='research'?'Ask the model to analyze a topic. External web search, browsing and research tools are not connected.':mode==='code'?'Ask for code, explanations or reviews. Code is returned as text; this page does not execute it.':'Send text to a selected API WILD model using your account credits.'}</p><label>Model<select value={model} disabled={busy||Boolean(pending)||messages.length>0} onChange={e=>setModel(e.target.value)}>{catalog.models.map(m=><option key={m.model_name} value={m.model_name} disabled={!routes.some((r:any)=>r.model===m.model_name)}>{m.creator} · {m.model_name}</option>)}</select></label><p>Input: {price(selected.apiwild_selling_price.input)} / 1M tokens · Output: {price(selected.apiwild_selling_price.output)} / 1M tokens. Base rates; conditional pricing is shown in the <a href={'/models/'+encodeURIComponent(model)}>model price details</a> apply. This playground requests up to {route?Math.min(512,route.maxOutputTokens):512} output tokens.</p>{loading?<p role="status">Loading availability…</p>:!ready?<p className="billing-notice">{availability?.inferenceConfigured===false?'Model execution is not configured yet. You cannot send a paid request from this page.':'No activated route is available for this model and capability. Choose an available model or refresh later.'}</p>:<p>Selected route is configured. Available credits and spending limits are verified before each request.</p>}{error&&<p role="alert" className="form-error">{error} <a href="/console/billing">Manage credits</a></p>}<div aria-live="polite">{messages.map((message,index)=><article className="console-panel" key={index}><strong>{message.role==='user'?'You':selected.creator}</strong><pre style={{whiteSpace:'pre-wrap'}}>{message.content}</pre></article>)}</div>{usage&&<p>Last response: {usage.prompt_tokens} input tokens · {usage.completion_tokens} output tokens.</p>}<form className="console-form" onSubmit={e=>{e.preventDefault();send()}}><label>Your message<textarea value={input} disabled={busy||Boolean(pending)} maxLength={16000} rows={5} onChange={e=>setInput(e.target.value)}/></label><button className="pill-button dark" disabled={busy||loading||!ready||Boolean(pending)||!input.trim()}>{busy?'Generating…':'Send message'}</button></form>{pending&&<div className="billing-notice"><p>This request has not been confirmed. Retrying reuses the same request identifier and body; it does not start a new request.</p><button disabled={busy} onClick={()=>send(true)}>Retry same request</button></div>}<button disabled={busy||Boolean(pending)} onClick={()=>{setMessages([]);setUsage(null);setError('')}}>New conversation</button></section>;
}
