'use client';
import {useEffect,useRef,useState} from 'react';
import {dictationDeadline,recognitionError,recognitionText} from '@/lib/owned-voice-controls.mjs';
type RecognitionResult={isFinal:boolean;[index:number]:{transcript:string}};
type RecognitionEvent={resultIndex:number;results:ArrayLike<RecognitionResult>};
type Recognition={lang:string;continuous:boolean;interimResults:boolean;onresult:((event:RecognitionEvent)=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
type RecognitionConstructor=new()=>Recognition;
function recognitionConstructor(){const browser=window as Window & {SpeechRecognition?:RecognitionConstructor;webkitSpeechRecognition?:RecognitionConstructor};return browser.SpeechRecognition||browser.webkitSpeechRecognition;}
export default function OwnedVoiceControls({disabled,onTranscript,assistantText}:{disabled:boolean;onTranscript:(text:string)=>void;assistantText:string}){
 const[dictationSupported,setDictationSupported]=useState(false),[playbackSupported,setPlaybackSupported]=useState(false),[listening,setListening]=useState(false),[speaking,setSpeaking]=useState(false),[interim,setInterim]=useState(''),[error,setError]=useState(''),[language,setLanguage]=useState('en-CA'),[voices,setVoices]=useState<SpeechSynthesisVoice[]>([]),[voiceUri,setVoiceUri]=useState('');
 const deadline=useRef<ReturnType<typeof dictationDeadline>|null>(null);
 const recognition=useRef<Recognition|null>(null),playback=useRef<SpeechSynthesisUtterance|null>(null),callback=useRef(onTranscript),disabledRef=useRef(disabled),mounted=useRef(true);
 callback.current=onTranscript;disabledRef.current=disabled;
 useEffect(()=>{mounted.current=true;setDictationSupported(Boolean(recognitionConstructor()));const synthesis=window.speechSynthesis;setPlaybackSupported(Boolean(synthesis&&window.SpeechSynthesisUtterance));const refresh=()=>{if(mounted.current)setVoices(synthesis?.getVoices()||[])};refresh();synthesis?.addEventListener('voiceschanged',refresh);return()=>{mounted.current=false;deadline.current?.cancel();deadline.current=null;const active=recognition.current;recognition.current=null;active?.abort();if(playback.current){playback.current=null;synthesis?.cancel()}synthesis?.removeEventListener('voiceschanged',refresh)}},[]);
 useEffect(()=>{if(disabled){deadline.current?.cancel();deadline.current=null;const active=recognition.current;recognition.current=null;active?.abort();setListening(false);setInterim('');stopPlayback()}},[disabled]);
 function stopDictation(){deadline.current?.cancel();deadline.current=null;recognition.current?.stop();}
 function startDictation(){if(disabledRef.current||recognition.current)return;stopPlayback();const Constructor=recognitionConstructor();if(!Constructor){setError('Dictation is unavailable in this browser. Type your message instead.');return;}setError('');setInterim('');const active=new Constructor();active.lang=language;active.continuous=true;active.interimResults=true;active.onresult=event=>{if(recognition.current!==active||disabledRef.current)return;const text=recognitionText(event);setInterim(text.interimText);if(text.finalText){try{callback.current(text.finalText)}catch(failure){setError((failure as Error).message);stopDictation()}}};active.onerror=event=>{if(recognition.current===active&&mounted.current&&event.error!=='aborted')setError(recognitionError(event.error))};active.onend=()=>{if(recognition.current===active){deadline.current?.cancel();deadline.current=null;recognition.current=null;if(mounted.current){setListening(false);setInterim('')}}};recognition.current=active;try{active.start();setListening(true);deadline.current=dictationDeadline(()=>{if(recognition.current===active){active.stop();if(mounted.current)setError('The 60-second dictation session ended. Review your words, or start again.')}})}catch{recognition.current=null;setError('Dictation could not start. Check microphone permissions or type your message.')}}
 function stopPlayback(){if(playback.current){playback.current=null;window.speechSynthesis.cancel();setSpeaking(false)}}
 function readAloud(){if(!playbackSupported||!assistantText||disabledRef.current)return;deadline.current?.cancel();deadline.current=null;const active=recognition.current;recognition.current=null;active?.abort();setListening(false);setInterim('');stopPlayback();setError('');const utterance=new SpeechSynthesisUtterance(assistantText);utterance.lang=language;const chosen=voices.find(voice=>voice.voiceURI===voiceUri);if(chosen)utterance.voice=chosen;utterance.onend=()=>{if(playback.current!==utterance)return;playback.current=null;if(mounted.current)setSpeaking(false)};utterance.onerror=event=>{if(playback.current!==utterance)return;playback.current=null;if(mounted.current){setSpeaking(false);if(event.error!=='canceled'&&event.error!=='interrupted')setError('Your device could not read this response. Try a different voice.')}};playback.current=utterance;setSpeaking(true);try{window.speechSynthesis.speak(utterance)}catch{playback.current=null;setSpeaking(false);setError('Your device could not start speech playback. Try a different voice.')}}
 const matchingVoices=voices.filter(voice=>voice.lang.toLowerCase().split('-')[0]===language.split('-')[0]);
 return <details className="console-panel owned-browser-voice"><summary><strong>Browser voice: dictation and read aloud</strong></summary><p>Dictate an editable message or listen to the latest model response. Voice support depends on your browser and device; these controls are not hosted audio API endpoints.</p><p>Start dictation only when you are ready to grant microphone access. Each session ends after 60 seconds; dictation and playback do not run together. Your browser may send audio to its speech provider; speech playback may also use a remote device voice. API WILD receives the transcript only when you send your message, using normal model credits.</p><label>Voice language<select value={language} disabled={listening||speaking||disabled} onChange={e=>{setLanguage(e.target.value);setVoiceUri('')}}><option value="en-CA">English (Canada)</option><option value="bn-BD">বাংলা (Bangladesh)</option></select></label>{dictationSupported?<><button type="button" disabled={disabled||listening} onClick={startDictation}>Start dictation (microphone permission)</button><button type="button" disabled={!listening} onClick={stopDictation}>Stop dictation</button></>:<p>Speech recognition is unavailable in this browser. You can still type your message.</p>}{listening&&<p role="status">Listening… Final words are added to your editable message. Stop before sending.</p>}{interim&&<p aria-live="polite">Heard so far: {interim}</p>}{playbackSupported?<><label>Playback voice<select value={voiceUri} disabled={speaking||disabled} onChange={e=>setVoiceUri(e.target.value)}><option value="">Device default for selected language</option>{matchingVoices.map(voice=><option key={voice.voiceURI} value={voice.voiceURI}>{voice.name} · {voice.lang}{voice.localService?' · on device':' · remote'}</option>)}</select></label><button type="button" disabled={disabled||!assistantText||speaking} onClick={readAloud}>Read latest response aloud</button><button type="button" disabled={!speaking} onClick={stopPlayback}>Stop playback</button>{speaking&&<p role="status">Reading the response aloud…</p>}{language==='bn-BD'&&!matchingVoices.length&&<p>No Bangla playback voice was reported by this device. Install a device voice or choose English.</p>}</>:<p>Speech playback is unavailable in this browser.</p>}{error&&<p role="alert" className="form-error">{error}</p>}</details>;
}
