'use client';
import {useEffect,useState} from 'react';
import {customerApi} from '@/lib/customer-api';
type Usage={currency:'USD';fundedUsdMicros:number;spentUsdMicros:number;reservedUsdMicros:number;paymentHoldUsdMicros:number;availableUsdMicros:number;completedRequests:number};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:6}).format(n/1e6);
export default function OwnedUsage(){const[data,setData]=useState<Usage|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');customerApi('/api/usage',{signal:controller.signal}).then(value=>{if(value.currency!=='USD'||['fundedUsdMicros','spentUsdMicros','reservedUsdMicros','paymentHoldUsdMicros','availableUsdMicros','completedRequests'].some(key=>!Number.isSafeInteger(value[key])))throw Error('Usage information could not be verified.');if(!controller.signal.aborted)setData(value)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[retry]);
 return <><section className="console-panel"><div className="billing-toolbar"><h2>Your API usage</h2><button disabled={loading} onClick={()=>setRetry(v=>v+1)}>Refresh</button></div>{error&&<p role="alert" className="form-error">{error}</p>}{loading&&!data?<p role="status">Loading recorded usage…</p>:data&&<><div className="metrics-grid">{[['Available credit',money(data.availableUsdMicros)],['Settled usage',money(data.spentUsdMicros)],['Reserved for requests',money(data.reservedUsdMicros)],['Payment holds',money(data.paymentHoldUsdMicros)],['Recorded funding',money(data.fundedUsdMicros)],['Completed requests',data.completedRequests.toLocaleString()]].map(([label,value])=><article className="metric-card" key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><p>Amounts come from your account ledger. Pending requests reserve credit until settlement; payment holds are shown separately.</p>{data.completedRequests===0&&<p>No completed requests are recorded yet.</p>}<p>Per-request token details are not available in this view.</p></>}</section><a className="text-link" href="/console/billing">Manage credits and payments</a></>;
}
