'use client';
import {useEffect,useState} from 'react';
import {customerApi} from '@/lib/customer-api';
type Policy={workspaceType:'personal';members:{customerId:string;role:string}[];roles:{name:string;permissions:string[]}[];capabilities:string[];dailyLimitUsdMicros:number;sharedMembershipEnabled:false};
const capabilities=['chat','code','research','voice','transcribe','speak'];
const permissionLabels:Record<string,string>={manage_keys:'Manage API keys',manage_billing:'Manage credits and billing',manage_guardrails:'Manage guardrails',view_usage:'View usage'};
function parsePolicy(value:any):Policy{if(value?.workspaceType!=='personal'||value.sharedMembershipEnabled!==false||!Array.isArray(value.members)||!Array.isArray(value.roles)||!Array.isArray(value.capabilities)||value.capabilities.some((c:any)=>!capabilities.includes(c))||!Number.isSafeInteger(value.dailyLimitUsdMicros)||value.dailyLimitUsdMicros<0)throw Error('Workspace policy could not be verified.');return value}
export default function WorkspacePolicy({section}:{section:'members'|'roles'|'guardrails'}){
 const[data,setData]=useState<Policy|null>(null),[selected,setSelected]=useState<string[]>([]),[daily,setDaily]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 function show(value:any){const policy=parsePolicy(value);setData(policy);setSelected(policy.capabilities);setDaily(String(policy.dailyLimitUsdMicros/1e6))}
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');customerApi('/api/workspace',{signal:controller.signal}).then(value=>{if(!controller.signal.aborted)show(value)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[retry]);
 async function save(e:React.FormEvent){e.preventDefault();if(busy||!data)return;setBusy(true);setError('');setNotice('');try{const amount=Number(daily),micros=Math.round(amount*1e6);if(!Number.isFinite(amount)||amount<0||!Number.isSafeInteger(micros)||micros>1000000000000||Math.abs(amount*1e6-micros)>0.0001)throw Error('Enter a daily limit between $0 and $1,000,000, with at most six decimal places.');show(await customerApi('/api/workspace',{method:'PATCH',body:JSON.stringify({capabilities:selected,dailyLimitUsdMicros:micros})}));setNotice('Spending settings saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="console-panel"><div className="billing-toolbar"><h2>{section==='members'?'Workspace members':section==='roles'?'Roles and permissions':'Daily spending limit'}</h2><button disabled={busy||loading} onClick={()=>setRetry(v=>v+1)}>Refresh</button></div>{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="billing-notice" role="status">{notice}</p>}{loading&&!data?<p role="status">Loading workspace policy…</p>:data&&<>{section==='members'?<><p>This is your personal workspace. Shared membership and invitations are not enabled.</p>{data.members.map(member=><div className="setting-row" key={member.customerId}><strong>Your account</strong><span>{member.role==='owner'?'Owner':member.role}</span></div>)}</>:section==='roles'?<><p>These are the permissions currently returned for your personal workspace. Shared roles cannot be assigned yet.</p>{data.roles.map(role=><article key={role.name}><h3>{role.name==='owner'?'Owner':role.name}</h3><ul>{role.permissions.map(permission=><li key={permission}>{permissionLabels[permission]??permission}</li>)}</ul></article>)}</>:<form className="console-form" onSubmit={save}><p>Set the most your account can spend in a day. This does not add credits.</p><details><summary>Advanced: allowed capabilities</summary><p>Allowing a capability does not activate a model or tool.</p><fieldset><legend>Allowed capabilities</legend>{capabilities.map(capability=><label key={capability}><input type="checkbox" checked={selected.includes(capability)} disabled={busy} onChange={e=>setSelected(current=>e.target.checked?[...current,capability]:current.filter(c=>c!==capability))}/>{capability}</label>)}</fieldset></details><label>Daily spending limit (USD)<input type="number" required min="0" max="1000000" step="0.000001" value={daily} disabled={busy} onChange={e=>setDaily(e.target.value)}/></label><p>Set the cap to $0 or clear all capabilities to block new requests. Existing requests and reservations remain subject to settlement. This limit does not add credits.</p><button className="pill-button dark" disabled={busy||loading}>{busy?'Saving…':'Save spending limit'}</button></form>}</>}</section>;
}
