'use client';
import {usePathname} from 'next/navigation';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {ChevronDown,ArrowUpRight,Menu} from 'lucide-react';
import {ApiWildBrand,ApiWildMark} from '@/app/api-wild-brand';
const platform=[['Chat','/console/chat'],['Code','/console/code'],['Research','/console/research'],['Model catalog','/models'],['AI agents & automation','/workspace/index.html#solutions'],['Integrations','/integrations'],['Routing & controls','/platform'],['Agent operations','/workspace/index.html#operations']];
const resources=[['Quickstart','/docs'],['Integration guides','/integrations'],['Changelog','/changelog'],['Service status','/status'],['Help & support','/support']];
function Drop({label,items}:{label:string,items:string[][]}){return <DropdownMenu><DropdownMenuTrigger className="nav-trigger">{label}<ChevronDown size={14}/></DropdownMenuTrigger><DropdownMenuContent className="nav-dropdown" align="start">{items.map(([name,url])=><DropdownMenuItem key={url} asChild><a href={url}>{name}<ArrowUpRight size={14}/></a></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>}
export function Header(){const path=usePathname();if(path.startsWith('/console')||path==='/models')return <header className="console-header"><a className="logo" href="/"><ApiWildBrand/></a><nav aria-label="Console navigation">{[['Models','/models'],['Chat','/console/chat'],['Code','/console/code'],['Research','/console/research'],['Usage','/console/usage'],['API keys','/console/api-keys'],['Billing','/console/billing']].map(([n,u])=><a className={path===u?'active':''} key={u} href={u}>{n}</a>)}</nav><div><a href="/docs">Docs ↗</a><a className="console-avatar" href="/console/profile" aria-label="Account settings"><ApiWildMark/></a></div></header>;return <header className="site-header"><a className="logo" href="/"><ApiWildBrand/></a><nav aria-label="Main navigation" className="desktop-nav"><Drop label="Platform" items={platform}/><a href="/eu-endpoint">EU Endpoint</a><a href="/security">Security</a><a href="/docs">Docs</a><a href="/pricing">Pricing</a><a href="/enterprise">Enterprise</a><Drop label="Resources" items={resources}/></nav><div className="nav-actions"><a className="signin" href="/login">Sign in</a><a className="pill-button dark" href="/signup">Get started <ArrowUpRight size={15}/></a><div className="mobile-nav"><Drop label="Menu" items={[...platform,...resources,['Pricing','/pricing'],['Enterprise','/enterprise'],['Security','/security'],['EU Endpoint','/eu-endpoint']]}/></div></div></header>}
export function Footer(){
 const path=usePathname();if(path.startsWith('/console'))return null;
 const groups=[{title:'Platform',links:[['Model catalog','/models'],['Pricing','/pricing'],['Agents & automation','/workspace/index.html#solutions'],['Integrations','/integrations'],['Enterprise','/enterprise']]},{title:'Developers',links:[['Documentation','/docs'],['API reference','/api-reference'],['Quickstart','/quickstart'],['Changelog','/changelog'],['Service status','/status']]},{title:'API WILD',links:[['About us','/about'],['Security','/security'],['Help & support','/support'],['Contact','/contact']]}];
 return <footer className="site-footer"><div className="footer-intro"><div><h2>Your next idea starts here.</h2><p>Discover models. Shape your AI stack.</p></div><a href="/models">Explore the catalog <ArrowUpRight size={17}/></a></div><div className="footer-top"><div className="footer-brand"><a className="logo" href="/" aria-label="API WILD home"><ApiWildBrand/></a><p>Model APIs, intelligent agents<br/>and business automation.</p><a className="footer-contact" href="mailto:support@apiwild.com">Get in touch ↗</a></div>{groups.map(group=><nav className="footer-column" key={group.title} aria-label={group.title+' footer links'}><h3>{group.title}</h3>{group.links.map(([name,url])=><a key={url} href={url}>{name}</a>)}</nav>)}</div><div className="footer-bottom"><span>© {new Date().getFullYear()} API WILD. All rights reserved.</span><nav className="footer-legal" aria-label="Legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/acceptable-use">Acceptable use</a></nav></div></footer>
}
