'use client';
import {useEffect,useRef,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {ArrowRight,ArrowUpRight,Code2,Layers,Workflow,ChevronLeft,ChevronRight,Pause,Play,Copy,Check,ShieldCheck,SlidersHorizontal,Globe2} from 'lucide-react';
import {ApiWildMark} from '@/app/api-wild-brand';
import {catalog as modelCatalog,price} from '@/lib/catalog';
const featuredModels=['openai','anthropic','google'].map(p=>modelCatalog.models.find(m=>m.provider===p&&m.output.includes('text')&&!m.id.includes(':'))).filter(m=>!!m);
const catalog='/models';
async function copyText(value:string){
 try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(value);return;}}catch{}
 const input=document.createElement('textarea');input.value=value;input.style.position='fixed';input.style.opacity='0';document.body.append(input);input.select();const ok=document.execCommand('copy');input.remove();if(!ok)throw Error('Select the example to copy it.');
}
export default function Landing(){const [paused,setPaused]=useState(false);const [word,setWord]=useState(0);const [copied,setCopied]=useState(false);const [reelPaused,setReelPaused]=useState(false);const reel=useRef<HTMLDivElement>(null);const words=['every model.','your agents.','what’s next.'];
useEffect(()=>{if(paused)return;const media=matchMedia('(prefers-reduced-motion: reduce)');if(media.matches){setPaused(true);return;}const timer=setInterval(()=>setWord(v=>(v+1)%3),3600);return()=>clearInterval(timer)},[paused]);
useEffect(()=>{if(paused)return;const cards=document.querySelectorAll('[data-reveal]');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}}),{threshold:.12});cards.forEach(c=>observer.observe(c));let ticking=false;const scroll=()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{document.querySelectorAll<HTMLElement>('[data-parallax]').forEach(el=>{const r=el.getBoundingClientRect();const y=Math.max(-28,Math.min(28,(window.innerHeight/2-r.top-r.height/2)*.06));el.style.setProperty('--drift',`${y}px`)});ticking=false})};window.addEventListener('scroll',scroll,{passive:true});return()=>{observer.disconnect();window.removeEventListener('scroll',scroll)}},[paused]);
useEffect(()=>{if(paused||reelPaused)return;const timer=setInterval(()=>{const el=reel.current;if(!el)return;const atEnd=el.scrollLeft+el.clientWidth>=el.scrollWidth-20;el.scrollTo({left:atEnd?0:el.scrollLeft+el.clientWidth*.75,behavior:'smooth'});},5000);return()=>clearInterval(timer)},[paused,reelPaused]);
return <main id="main" className={paused?'landing motion-paused':'landing'}>
<section className="hero"><div className="hero-badge"><ApiWildMark className="mini-api-wild-mark"/> Models. Agents. Automation. <ArrowUpRight size={13}/></div><h1>One platform.<br/>Built for <span key={word} className="rotating-word">{words[word]}</span></h1><p className="hero-description">Find the right model. Build a tailored agent.<br/>Connect the intelligence your business runs on.</p><div className="hero-ctas"><a href="/signup" className="pill-button dark">Build your AI stack <ArrowUpRight size={17}/></a><a href={catalog} className="pill-button outline">Explore the marketplace <ArrowRight size={17}/></a></div><div className="hero-proof"><span>Model API plans</span><i/> <span>Custom engineering</span><i/><span>Business automation</span></div><div className="hero-categories"><a href={catalog}><Code2/><div><strong>Model APIs</strong><p>Explore routes for code, chat and reasoning.</p></div><ArrowUpRight size={17}/></a><a href="/workspace/index.html#solutions"><Layers/><div><strong>Tailored agents</strong><p>Designed for the work your team needs.</p></div><ArrowUpRight size={17}/></a><a href="/integrations"><Workflow/><div><strong>Connected workflows</strong><p>Plan the handoffs between your tools.</p></div><ArrowUpRight size={17}/></a></div><div className="hero-caption">Create an account to save your setup. Model provisioning and billing are not yet available.</div></section>
<section className="ecosystem"><div className="section-overline">THE GLOBAL AI ECOSYSTEM</div><h2>Built around the tools you know.</h2><p>Provider ecosystem under evaluation. Logos identify providers, not API WILD customers or confirmed integrations.</p><div className="marquee" aria-label="AI provider ecosystem"><div className="marquee-track">{[0,1].map(n=><div className="logo-group" key={n} aria-hidden={n===1}>{['OpenAI','Claude','Gemini','DeepSeek','Qwen','Mistral','Kimi'].map(name=><span className="provider-logo" key={name}><img src={'/providers/'+name.toLowerCase()+'.svg'} alt="" onError={e=>e.currentTarget.style.display='none'}/>{name}</span>)}</div>)}</div></div><button className="motion-control" onClick={()=>setPaused(!paused)}>{paused?<Play size={13}/>:<Pause size={13}/>} {paused?'Play animations':'Pause animations'}</button></section>
<section className="section showcase" data-reveal><div className="section-heading"><div><span className="section-overline">BEYOND THE CHAT BOX</span><h2>Make room for<br/>something extraordinary.</h2></div><div><p>From affordable model access to the workflows behind it.<br/>Build your AI stack without enterprise-size costs.</p><div className="carousel-buttons"><button aria-label="Previous showcase" onClick={()=>reel.current?.scrollBy({left:-410,behavior:'smooth'})}><ChevronLeft size={20}/></button><button aria-label="Next showcase" onClick={()=>reel.current?.scrollBy({left:410,behavior:'smooth'})}><ChevronRight size={20}/></button></div></div></div><div className="showcase-reel" ref={reel} onMouseEnter={()=>setReelPaused(true)} onMouseLeave={()=>setReelPaused(false)} onFocusCapture={()=>setReelPaused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setReelPaused(false)}} tabIndex={0} aria-label="API WILD capabilities carousel"><article className="media-card ar-marketplace-card" data-parallax><img src="/gallery/api-marketplace-ar.png" alt="Futuristic holographic globe connecting multiple AI model endpoints"/><div className="ar-scan" aria-hidden="true"/><div className="media-caption"><span>GLOBAL MODEL ACCESS</span><h3>Built to be the world’s most affordable API marketplace.</h3><a href="/models">Explore model APIs <ArrowUpRight size={16}/></a></div></article><article className="media-card crop-two" data-parallax><img src="/gallery/chrome.png" alt="Reflective chrome infinity sculpture representing a tailored AI solution"/><div className="media-caption"><span>DESIGNED AROUND YOU</span><h3>From concept to a custom brief.</h3><a href="/workspace/index.html#solutions">Design a solution <ArrowUpRight size={16}/></a></div></article><article className="media-card code-card" data-parallax><div className="editor-label">workflow.config</div><pre>{`{
  "trigger": "new_message",
  "agent": "support",
  "knowledge": "your_business",
  "escalation": "human",
  "budget": "your_limits"
}`}</pre><div className="media-caption"><span>BUSINESS AUTOMATION</span><h3>Your workflow. In motion.</h3><a href="/workspace/index.html#operations">Explore agent operations <ArrowUpRight size={16}/></a></div></article></div></section>
<section className="section demo-section" data-reveal><div className="center-heading"><span className="section-overline">ONE CONSISTENT STARTING POINT</span><h2>Models, agents and workflows.<br/>One place to build.</h2><p>Explore the proposed request patterns before you integrate.</p></div><Tabs defaultValue="text" className="api-demo"><TabsList className="demo-tabs"><TabsTrigger value="text">Model API</TabsTrigger><TabsTrigger value="agent">AI agent</TabsTrigger><TabsTrigger value="workflow">Automation</TabsTrigger></TabsList>{[['text','POST /v1/chat/completions','{\n  "model": "openai/gpt-6-astra",\n  "messages": [\n    {"role": "user", "content": "Build what’s next."}\n  ]\n}','One familiar API pattern.','Compare models for chat, coding and reasoning.','/docs'],['agent','DRAFT / agent specification','{\n  "role": "Customer support",\n  "sources": ["Your knowledge base"],\n  "autonomy": "Routine replies",\n  "handoff": "Your team"\n}','An agent with a clear job.','Choose your knowledge sources, tools and approval boundaries.','/workspace/index.html#solutions'],['workflow','DRAFT / automation specification','{\n  "trigger": "Customer intake",\n  "steps": ["Classify", "Enrich", "Route"],\n  "approval": "Before external actions",\n  "on_error": "Pause and notify"\n}','Connect the work between tools.','Define triggers, tasks and handoffs in a downloadable solution brief.','/integrations']].map(([id,label,code,title,desc,url])=><TabsContent key={id} value={id}><div className="demo-grid"><div className="code-window"><div className="code-top"><span>{label}</span><button className="copy-code" onClick={async()=>{try{await copyText(code);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{setCopied(false)}}}>{copied?<Check size={13}/>:<Copy size={13}/>} {copied?'Copied':'Copy'}</button></div><pre>{code}</pre></div><div className="demo-description"><ApiWildMark className="mini-api-wild-mark"/><h3>{title}</h3><p>{desc}</p><a href={url}>Explore the guide <ArrowRight size={16}/></a><small>Live inference and agent execution are not connected.</small></div></div></TabsContent>)}</Tabs></section>
<section className="section" data-reveal><div className="section-heading"><div><span className="section-overline">CLEAR PRICING, BETTER DECISIONS</span><h2>Know the cost.<br/>Choose your next move.</h2></div><a className="text-link" href="/pricing">Explore all pricing <ArrowRight size={18}/></a></div><div className="landing-price-table"><div className="price-table-head"><span>MODEL ROUTE</span><span>INPUT / 1M TOKENS</span><span>OUTPUT / 1M TOKENS</span></div>{featuredModels.map(m=><a href="/pricing" key={m.id} className="price-table-row"><div className="landing-model-name"><img src={m.logo} alt={m.providerName} width="30" height="30"/><div><strong>{m.shortName}</strong><small>{m.providerName}</small></div></div><span>{price(m.pricing.input)}</span><span>{price(m.pricing.output)}<ArrowUpRight size={17}/></span></a>)}</div><p className="section-fine">OpenRouter reference rates in USD. Tiered, cache and tool pricing are listed in the model directory. API WILD inference is not yet activated.</p></section>
<section className="section integrations-section" data-reveal><div><span className="section-overline">FIT YOUR EXISTING STACK</span><h2>Your tools.<br/>Your way of working.</h2><p>Start with an integration brief for the systems you use.<br/>Keep the workflow familiar as your capabilities grow.</p><a href="/integrations" className="pill-button dark">Explore integrations <ArrowUpRight size={16}/></a></div><div className="integration-tiles">{[['Python','SDK & HTTP'],['Node.js','SDK & HTTP'],['cURL','REST requests'],['Messenger','Support workflows'],['CRM','Leads & records'],['Webhooks','Event-driven tasks']].map(([name,sub])=><a href="/integrations" key={name}><span>{name}</span><small>{sub}</small><ArrowUpRight size={16}/></a>)}</div></section>
<section className="section advantages" data-reveal><div className="center-heading"><span className="section-overline">INTELLIGENCE WITH INTENTION</span><h2>A better foundation<br/>for what comes next.</h2></div><div className="benefit-grid">{[[Code2,'Compare before you commit','Explore model routes and estimate your token budget.','/pricing'],[Workflow,'Built around the job','Define your business logic, integrations and desired outcomes.','/workspace/index.html#solutions'],[SlidersHorizontal,'Set your boundaries','Specify operating budgets, approval gates and human handoffs.','/workspace/index.html#operations'],[Layers,'Keep your plans together','Save your profile and download your stack or solution brief.','/account'],[ShieldCheck,'Understand the data flow','Review current data handling and service limitations.','/security'],[Globe2,'Plan for your organization','Document regional processing, team and support requirements.','/enterprise']].map(([Icon,title,desc,url])=>{const I=Icon as typeof Code2;return <a className="benefit" key={String(title)} href={String(url)}><I size={23}/><h3>{String(title)}</h3><p>{String(desc)}</p><ArrowUpRight size={17}/></a>})}</div></section>
<section className="section setup-section" data-reveal><div className="center-heading"><span className="section-overline">A SMALL FIRST STEP</span><h2>From an idea<br/>to your AI workspace.</h2></div><div className="setup-steps">{[['01','Create your profile','Sign in securely and tell us what you’re building.'],['02','Choose your starting point','Compare models or define a tailored agent and workflow.'],['03','Save your next move','Keep your customer profile and preferences in your account.']].map(([n,t,p])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></div>)}</div></section>
<section className="final-cta"><span className="section-overline">BUILD SOMETHING THAT MATTERS</span><h2>Your next chapter.<br/><em>Powered by intelligence.</em></h2><a href="/signup" className="pill-button dark">Create your workspace <ArrowUpRight size={18}/></a><p>Start with a plan. Build toward production.</p></section>
</main>}
