'use client';
import {useEffect,useRef,useState} from 'react';
import {promotionalCheckoutRemaining,verifiedCreditOffers,type CreditOffers,type CreditPack} from '@/lib/owned-credit-offers.mjs';
import './public-credit-pack-cards.css';
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:cents%100?2:0,maximumFractionDigits:2}).format(cents/100);
const localDate=(value:string)=>new Intl.DateTimeFormat('en-CA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
const utcDate=(value:string)=>new Date(value).toISOString().replace('T',' ').replace('.000Z',' UTC');
function remainingLabel(milliseconds:number){const seconds=Math.floor(milliseconds/1000),days=Math.floor(seconds/86400),hours=Math.floor(seconds%86400/3600),minutes=Math.floor(seconds%3600/60);return `${days}d ${hours}h ${minutes}m ${seconds%60}s`}

export function CreditPackCards({offers,disabled=false,onChoose,onRefresh}:{offers:CreditOffers;disabled?:boolean;onChoose?:(pack:CreditPack)=>void;onRefresh?:()=>void}){
 const[now,setNow]=useState(()=>Date.now());
 const refreshed=useRef<string|null>(null);
 const remaining=promotionalCheckoutRemaining(offers,now),stale=offers.promotion.active&&remaining===0;
 useEffect(()=>{setNow(Date.now());if(!offers.promotion.active)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[offers]);
 useEffect(()=>{if(!stale||!onRefresh)return;const identity=offers.promotion.id+':'+offers.promotion.checkoutClosesAt;if(refreshed.current===identity)return;refreshed.current=identity;onRefresh()},[stale,offers,onRefresh]);
 return <section className="credit-pack-offers" aria-labelledby="credit-pack-heading"><div className="credit-pack-heading"><div><span className="section-overline">ONE-TIME USD CREDIT PACKS</span><h2 id="credit-pack-heading">Choose your next step.</h2><p>One prepaid wallet for the website and API. Model usage follows API WILD’s published retail rates.</p></div><a className="text-link" href="/models">Compare our rates →</a></div>{offers.promotion.active&&!stale?<div className="credit-pack-promotion"><strong>15-day purchase promotion</strong><span>Time left to start a promotional checkout: <b>{remainingLabel(remaining)}</b></span><p>Start checkout by <time dateTime={offers.promotion.checkoutClosesAt!}>{localDate(offers.promotion.checkoutClosesAt!)}</time> on your device ({utcDate(offers.promotion.checkoutClosesAt!)}). Complete checkout before it expires. Credits and bonus are added after verified successful payment.</p></div>:<p className="credit-pack-note">{stale?'The promotional checkout window has closed. Refresh to confirm current pack totals.':offers.promotion.endsAt?'The promotional checkout window is not active. Current pack totals are shown below.':'Current one-time pack totals are shown below.'}</p>}{stale?<button className="pill-button outline" disabled={disabled} onClick={onRefresh}>Refresh credit offers</button>:<div className="credit-pack-grid">{offers.packages.map(pack=><article className="credit-pack-card" key={pack.id}><span className="credit-pack-name">{pack.name}</span><h3>{money(pack.priceCents)} <small>USD · one payment</small></h3><dl><div><dt>Purchase credit</dt><dd>{money(pack.priceCents)}</dd></div><div><dt>Promotional bonus</dt><dd>{pack.bonusCents>0?'+':''}{money(pack.bonusCents)}</dd></div><div className="credit-pack-total"><dt>Total wallet credit</dt><dd>{money(pack.totalCreditCents)}</dd></div></dl>{onChoose?<button className="pill-button dark" type="button" disabled={disabled} onClick={()=>onChoose(pack)}>Choose {pack.name}</button>:<a className="pill-button dark" href={'/console/billing?package='+pack.id}>Open Credits · {pack.name}</a>}</article>)}</div>}<p className="credit-pack-note">Credit and any eligible bonus are added only after verified successful payment. These are one-time purchases, with no recurring subscription. The 15-day window concerns new promotional purchases; it is not a promised renewal.</p></section>;
}

export default function PublicCreditPackCards(){
 const[offers,setOffers]=useState<CreditOffers|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();let live=true;setOffers(null);setError('');const timer=setTimeout(()=>controller.abort(),10000);(async()=>{const response=await fetch('/api/billing/offers',{cache:'no-store',credentials:'omit',redirect:'error',signal:controller.signal});if(!response.ok||!/^application\/json(?:\s*;|$)/i.test(response.headers.get('content-type')||''))throw Error('Unavailable offers');const value=verifiedCreditOffers(await response.json());if(live)setOffers(value)})().catch(()=>{if(live)setError('Credit offers are temporarily unavailable. Please retry.')}).finally(()=>clearTimeout(timer));return()=>{live=false;clearTimeout(timer);controller.abort()}},[retry]);
 if(offers)return <CreditPackCards offers={offers} onRefresh={()=>setRetry(value=>value+1)}/>;
 return <section className="credit-pack-offers"><h2>One-time credit packs</h2>{error?<p role="alert">{error} <button className="pill-button outline" onClick={()=>setRetry(value=>value+1)}>Retry offers</button></p>:<p role="status">Loading current credit offers…</p>}</section>;
}
