'use client';
import {useEffect,useState} from 'react';
import {MessageSquare,Code2,Search,ArrowUpRight} from 'lucide-react';
import {gatewayModels,creditPacks} from '@/lib/gateway-catalog';
const descriptions=['Conversation, ideas and spoken replies.','Write, review and explain code with DeepSeek.','Answers grounded in current web sources.'];
const icons=[MessageSquare,Code2,Search];
export default function RouteCards({packs=false}:{packs?:boolean}){
 const[ready,setReady]=useState<Record<string,boolean>|null>(null);
 useEffect(()=>{const c=new AbortController();fetch('/api/gateway/config',{signal:c.signal,cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(v=>setReady(v.ready)).catch(()=>{});return()=>c.abort()},[]);
 return <section className="route-offering"><div className="offering-title"><span className="section-overline">ONE ACCOUNT. THREE WAYS TO BUILD.</span><h2>Chat. Code. Research.</h2><p>Choose the task. API WILD connects the right services behind the scenes.</p></div><div className="route-grid">{gatewayModels.map((m,i)=>{const Icon=icons[i],mode=m.name.toLowerCase();return <article className="route-card" key={m.id}><div className="route-card-top"><Icon size={24}/><span className={'route-status '+(ready?.[mode]?'ready':'')}>{ready===null?'Checking availability':ready[mode]?'Available':'Awaiting activation'}</span></div><h3>{m.name}</h3><p>{descriptions[i]}</p><small>{m.engine}</small><dl><div><dt>Input / 1M tokens</dt><dd>${m.input.toFixed(2)}</dd></div><div><dt>Output / 1M tokens</dt><dd>${m.output.toFixed(2)}</dd></div>{mode==='research'&&<div><dt>Web search</dt><dd>$0.005 / search</dd></div>}</dl><a className="pill-button outline" href={'/console/'+mode}>Open {m.name}<ArrowUpRight size={15}/></a></article>})}</div><p className="section-fine">USD usage rates. Voice adds $0.0043 per audio minute for transcription and $0.030 per 1,000 spoken characters. Responses are billed by measured usage. Availability is shown above.</p>{packs&&<><div className="offering-title"><h2>One balance for everything.</h2><p>Buy prepaid credits once. Use them across Chat, Code, Research and voice, at the same rates in every pack.</p></div><div className="billing-packs">{creditPacks.map(p=><article className="billing-pack" key={p.id}><span>{p.name}</span><h3>${p.cents/100}</h3><p>{p.description}</p><a className="pill-button dark" href="/console/billing">Add credits →</a></article>)}</div><p className="section-fine">One-time USD purchases. No recurring subscription. Purchase availability and any applicable tax are shown before payment.</p></>}</section>;
}
