'use client';
import {MessageSquare,Code2,Search,ArrowUpRight} from 'lucide-react';
import {gatewayModels,creditPacks} from '@/lib/gateway-catalog';
import selected from '@/data/selected-supplier-models.json';
const descriptions=['Planned text conversations.','Planned coding requests.','Planned research workflows.'];
const icons=[MessageSquare,Code2,Search];
const usd=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:8}).format(value);
export default function RouteCards({packs=false}:{packs?:boolean}){
 return <section className="route-offering"><div className="offering-title"><span className="section-overline">PLANNED WORKSPACE TOOLS</span><h2>Chat. Code. Research.</h2><p>Model rates below come from the approved catalogue. Task connections and customer inference are not activated.</p></div><div className="route-grid">{gatewayModels.map((m,i)=>{const Icon=icons[i],mode=m.name.toLowerCase(),retail=selected.models.find(model=>model.model_name===m.model)?.apiwild_selling_price;return <article className="route-card" key={m.id}><div className="route-card-top"><Icon size={24}/><span className="route-status">Not activated</span></div><h3>{m.name}</h3><p>{descriptions[i]}</p><small>{m.model}</small><dl><div><dt>Approved model input / 1M tokens</dt><dd>{retail?usd(retail.input):'Not set'}</dd></div><div><dt>Approved model output / 1M tokens</dt><dd>{retail?usd(retail.output):'Not set'}</dd></div></dl>{retail?.peak&&<p className="section-fine">Off-peak base rates. Peak and conditional prices are listed in the model catalogue.</p>}<a className="pill-button outline" href="/models">View model prices<ArrowUpRight size={15}/></a></article>})}</div><p className="section-fine">Uncached model token rates in USD. Supplier identity and task routing remain unverified. Search, voice, media and tool add-on prices have not been approved.</p>{packs&&<><div className="offering-title"><h2>Planned credit options.</h2><p>Customer credit purchases are not activated. These workspace options do not enable model access.</p></div><div className="billing-packs"><article className="billing-pack"><span>Noob</span><h3>Pay as you go</h3><p>Planned flexible prepaid balance.</p><a className="pill-button dark" href="/console/billing">View billing →</a></article>{creditPacks.map(p=><article className="billing-pack" key={p.id}><span>{p.name}</span><h3>${p.cents/100}</h3><p>{p.description}</p><a className="pill-button dark" href="/console/billing">View billing →</a></article>)}</div><p className="section-fine">Planned one-time USD credit options. Purchases, customer charging and inference are not activated.</p><div className="offering-title"><h2>A little more you.</h2><p>Student or alumni project? A business workflow that needs a tailored solution? Tell us what you are building. Custom work is scoped and quoted separately from model usage.</p><a className="pill-button outline" href="/contact">Discuss a tailored solution →</a></div></>}</section>;
}
