'use client';
import {MessageSquare,Code2,Search,ArrowUpRight} from 'lucide-react';
import {gatewayModels} from '@/lib/gateway-catalog';
import selected from '@/app/models/public-models.json';
const descriptions=['Text conversations with a selected available model.','Request code, explanations and reviews as text.','Analyze topics as text; no web search or browsing.'];
const icons=[MessageSquare,Code2,Search];
const usd=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:8}).format(value);
export default function RouteCards({packs=false}:{packs?:boolean}){
 return <section className="route-offering"><div className="offering-title"><span className="section-overline">TEXT WORKSPACE MODES</span><h2>Chat. Code. Research.</h2><p>Model rates below are catalogue references. Choose a currently available model in the playground; modes do not guarantee a fixed model route.</p></div><div className="route-grid">{gatewayModels.map((m,i)=>{const Icon=icons[i],retail=selected.models.find(model=>model.model_name===m.model)?.apiwild_selling_price;return <article className="route-card" key={m.id}><div className="route-card-top"><Icon size={24}/><span className="route-status">Check availability</span></div><h3>{m.name}</h3><p>{descriptions[i]}</p><small>{m.model}</small><dl><div><dt>Approved model input / 1M tokens</dt><dd>{retail?usd(retail.input):'Not set'}</dd></div><div><dt>Approved model output / 1M tokens</dt><dd>{retail?usd(retail.output):'Not set'}</dd></div></dl>{retail?.peak&&<p className="section-fine">Off-peak base rates. Peak and conditional prices are listed in the model catalogue.</p>}<a className="pill-button outline" href="/models">View model prices<ArrowUpRight size={15}/></a></article>})}</div><p className="section-fine">Uncached model token rates in USD. Check current route availability before sending a request. Search, voice, media and tool add-on prices have not been approved.</p>{packs&&<><div className="offering-title"><h2>One prepaid USD wallet.</h2><p>Check the Credits page for purchase availability. Add credit from $30 when available and use it across activated models.</p></div><div className="billing-packs"><article className="billing-pack"><span>API WILD credits</span><h3>$30 minimum</h3><p>A $30 top-up adds $30 to your wallet. Usage is deducted at each selected model’s published API WILD retail rates.</p><a className="pill-button dark" href="/console/billing">View wallet →</a></article></div><p className="section-fine">One-time USD top-ups. Check current model and purchase availability in your workspace. Spending limits do not add credit or guarantee a fixed number of tokens.</p><div className="offering-title"><h2>A little more you.</h2><p>Student or alumni project? A business workflow that needs a tailored solution? Tell us what you are building. Custom work is scoped and quoted separately from model usage.</p><a className="pill-button outline" href="/contact">Discuss a tailored solution →</a></div></>}</section>;
}
