// Shared display contract. Importing this module never bundles the legacy catalogue.
export type PriceTier={sku_label:string;price:string};
export type DisplayPrice={kind:string;sku_label:string;price:string;displayMultiplier:number;unitLabel:string;tiers?:PriceTier[];currency?:string};
export type SupplierOffer={id:number;providerId:number;providerSlug:string;providerName:string;upstreamModel:string;category:string;context:number;endpoints:{protocol:string;path:string;method:string}[];endpointParseError:boolean;currency:string;billingMode:string;inputPrice:string|null;outputPrice:string|null;fixedPrice:string|null;billingExpression:string|null;cachePrices:Record<string,string|null>;pricingAuthoritative:boolean;cachePricingAuthoritative:boolean;source:string;officialChannelId:number|null;reportedFeatures:unknown;platformEvidence:Record<string,unknown>;stationListed:'unknown';callable:false;tested:'not-run'};
export type CatalogModel={id:string;name:string;shortName:string;provider:string;providerName:string;logo:string;context:number;input:string[];output:string[];parameters:string[];pricing:{input:string|null;output:string|null};displayPricing:DisplayPrice[];created:number;description:string;sourceUrl:string;previewImage:string|null;pricingUnresolved:boolean;subrouter?:{offers:SupplierOffer[];pricingIndexPresent:boolean;advertisedProtocols:string[]}};
export type CatalogSnapshot={models:CatalogModel[];source:string;fetchedAt:string;count:number;subrouter?:{schemaVersion:number;providerCount:number;offerCount:number;marketplaceModelCount:number;pricingIndexCount:number;pricingOnlyCount:number;currencies:string[];billingModes:Record<string,number>;stale:boolean;refreshError:string|null}};
export function dollars(amount:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:10}).format(amount);}
export function currencyAmount(amount:number,currency='USD'){if(!Number.isFinite(amount)||amount<0)return 'Quote unavailable';if(!/^[A-Z]{3}$/.test(currency))return `${amount} (currency unknown)`;return new Intl.NumberFormat('en-US',{style:'currency',currency,currencyDisplay:'code',maximumFractionDigits:10}).format(amount);}
export function price(value:string|null){if(value===null||!Number.isFinite(Number(value))||Number(value)<0)return 'Dynamic';const amount=Number(value)*1e6;return amount===0?'Free':dollars(amount);}
export function displayPrice(row:DisplayPrice,value=row.price){const n=Number(value);return !Number.isFinite(n)||n<0?'Dynamic':row.currency?currencyAmount(n*row.displayMultiplier,row.currency):dollars(n*row.displayMultiplier);}
export function textInputPrice(model:CatalogModel){const row=model.displayPricing.find(r=>r.kind==='token'&&r.sku_label==='Input Price');const n=row?Number(row.price):NaN;return Number.isFinite(n)&&n>=0?n:Infinity;}
export function supplierQuote(value:string|null,currency:string){return value===null?'Quote unavailable':currencyAmount(Number(value),currency);}
