export type CreditPack = Readonly<{id:'smart'|'nerd'|'newton'|'alien';name:string;priceCents:number;bonusCents:number;totalCreditCents:number}>;
export type TemporaryCreditOffer = Readonly<{id:'launch-dollar';name:'API WILD $1 credits';priceCents:100;bonusCents:0;totalCreditCents:100;endsAt:string}>;
type CheckoutPackageId = CreditPack['id'] | TemporaryCreditOffer['id'];
export type CreditOffers = Readonly<{authority:'apiwild-owned-billing';currency:'USD';promotion:Readonly<{id:string;startsAt:string|null;endsAt:string|null;checkoutClosesAt:string|null;active:boolean}>;packages:readonly CreditPack[]}>;
export const CREDIT_PACK_NAMES:Readonly<Record<CreditPack['id'],string>>;
export function verifiedCreditOffers(data:unknown):CreditOffers;
export function promotionalCheckoutRemaining(offers:CreditOffers,now?:number):number;
export function verifiedTemporaryCreditOffer(data:unknown,now?:number):TemporaryCreditOffer|null;
export function checkoutStorageKey(identity:{amountCents?:number;packageId?:CheckoutPackageId;promotionId?:string}):string;
export type CheckoutRequest={key:string;requestId:string;body:{packageId:CheckoutPackageId;requestId:string}|{amountCents:number;requestId:string}};
export function checkoutRequest(storage:Pick<Storage,'getItem'|'setItem'>,identity:{amountCents?:number;packageId?:CheckoutPackageId;promotionId?:string},createId?:()=>string):CheckoutRequest;
export function saveCheckoutOrder(storage:Pick<Storage,'setItem'>,request:CheckoutRequest,orderId:unknown):void;
export function saveFailedCheckoutOrder(storage:Pick<Storage,'setItem'>,request:CheckoutRequest,error:unknown):void;
export function clearConfirmedCheckouts(storage:Pick<Storage,'getItem'|'removeItem'>,orders:Record<string,unknown>[],currentPromotionId?:string):void;
