import {database,respond,RequestError,readTextBounded,trustedWrite} from '@/db/service';
import {billingIdentity} from '@/lib/billing-auth';
import {billingOwner,billingConfig} from '@/lib/billing';
import {hashKey} from '@/lib/key-auth';
import {z} from 'zod';
async function owner(r:Request){return billingOwner((await billingIdentity(r,true)).id);}
function error(e:unknown){return respond({error:e instanceof RequestError?e.message:'API keys could not be updated.'},e instanceof RequestError?e.status:e instanceof SyntaxError?400:503);}
export async function GET(r:Request){try{const id=await owner(r);return respond({keys:(await database().prepare('SELECT id,name,prefix,scopes,daily_limit_micros,total_limit_micros,expires_at,revoked_at,last_used_at,created_at FROM gateway_keys WHERE user_id=? ORDER BY created_at DESC').bind(id).all()).results});}catch(e){return error(e);}}
export async function POST(r:Request){try{if(!trustedWrite(r))throw new RequestError('Invalid request origin.',403);const id=await owner(r);const b=z.object({name:z.string().trim().min(1).max(60),days:z.union([z.literal(7),z.literal(30),z.literal(90)]),scopes:z.array(z.enum(['chat','code','research','voice','transcribe','speak'])).min(1).max(6),dailyLimitDollars:z.number().positive().max(1000),totalLimitDollars:z.number().positive().max(10000)}).strict().safeParse(JSON.parse(await readTextBounded(r,2000)));if(!b.success)throw new RequestError('Enter a name, expiry, capabilities and spending limits.',400);const token='aw_'+billingConfig().mode+'_'+[...crypto.getRandomValues(new Uint8Array(32))].map(v=>v.toString(16).padStart(2,'0')).join(''),now=new Date().toISOString(),expires=new Date(Date.now()+b.data.days*86400000).toISOString();const result=await database().prepare('INSERT INTO gateway_keys(id,user_id,name,prefix,hash,scopes,daily_limit_micros,total_limit_micros,expires_at,created_at) SELECT ?,?,?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM gateway_keys WHERE user_id=? AND revoked_at IS NULL AND expires_at>?)<20').bind(crypto.randomUUID(),id,b.data.name,token.slice(0,16),await hashKey(token),JSON.stringify([...new Set(b.data.scopes)]),Math.round(b.data.dailyLimitDollars*1e6),Math.round(b.data.totalLimitDollars*1e6),expires,now,id,now).run();if(!result.meta.changes)throw new RequestError('Limit reached: revoke an existing key first.',409);return respond({key:token,expiresAt:expires},201);}catch(e){return error(e);}}
export async function DELETE(r:Request){try{if(!trustedWrite(r))throw new RequestError('Invalid request origin.',403);const id=await owner(r);const b=z.object({id:z.string().uuid()}).safeParse(JSON.parse(await readTextBounded(r,1000)));if(!b.success)throw new RequestError('Invalid key.',400);const result=await database().prepare('UPDATE gateway_keys SET revoked_at=? WHERE id=? AND user_id=? AND revoked_at IS NULL').bind(new Date().toISOString(),b.data.id,id).run();if(!result.meta.changes)throw new RequestError('Active key not found.',404);return respond({revoked:true});}catch(e){return error(e);}}
