import { sqliteTable, text, integer, index, uniqueIndex, primaryKey } from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{userId:text('user_id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),company:text('company').notNull(),useCase:text('use_case').notNull(),budget:integer('budget').notNull(),stack:text('stack').notNull().default('[]'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()});
export const briefs=sqliteTable('briefs',{id:text('id').notNull(),userId:text('user_id').notNull(),title:text('title').notNull(),content:text('content').notNull(),createdAt:text('created_at').notNull()},t=>[primaryKey({columns:[t.userId,t.id]}),index('idx_briefs_owner_created').on(t.userId,t.createdAt)]);
export const preferences=sqliteTable('preferences',{userId:text('user_id').primaryKey(),accountType:text('account_type').notNull().default('company'),domain:text('domain').notNull().default(''),phone:text('phone').notNull().default(''),country:text('country').notNull().default(''),building:text('building').notNull().default('[]'),compliance:text('compliance').notNull().default('[]'),project:text('project').notNull().default(''),retentionDays:integer('retention_days').notNull().default(30),updatedAt:text('updated_at').notNull()});
export const apiKeys=sqliteTable('api_keys',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),prefix:text('prefix').notNull(),hash:text('hash').notNull().unique(),scope:text('scope').notNull().default('read'),expiresAt:text('expires_at'),revokedAt:text('revoked_at'),lastUsedAt:text('last_used_at'),createdAt:text('created_at').notNull()},t=>[index('idx_keys_owner').on(t.userId)]);
export const usage=sqliteTable('usage_events',{id:text('id').primaryKey(),userId:text('user_id').notNull(),keyId:text('key_id'),model:text('model').notNull(),provider:text('provider').notNull(),status:text('status').notNull(),inputTokens:integer('input_tokens').notNull().default(0),outputTokens:integer('output_tokens').notNull().default(0),costMicros:integer('cost_micros').notNull().default(0),latencyMs:integer('latency_ms').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('idx_usage_owner_date').on(t.userId,t.createdAt)]);
export const orders=sqliteTable('billing_orders',{id:text('id').primaryKey(),userId:text('user_id').notNull(),requestId:text('request_id').notNull(),pack:text('pack').notNull(),amountCents:integer('amount_cents').notNull(),currency:text('currency').notNull(),sessionId:text('session_id').unique(),paymentIntent:text('payment_intent').unique(),status:text('status').notNull().default('created'),createdAt:text('created_at').notNull()},t=>[index('idx_orders_owner').on(t.userId),uniqueIndex('idx_order_retry').on(t.userId,t.requestId)]);
export const ledger=sqliteTable('credit_ledger',{id:text('id').primaryKey(),userId:text('user_id').notNull(),source:text('source').notNull().unique(),orderId:text('order_id').notNull(),amountCents:integer('amount_cents').notNull(),currency:text('currency').notNull(),description:text('description').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_ledger_owner').on(t.userId)]);
export const billingCustomers=sqliteTable('billing_customers',{userId:text('user_id').primaryKey(),stripeCustomerId:text('stripe_customer_id').unique(),createdAt:text('created_at').notNull()});
export const billingEvents=sqliteTable('billing_events',{id:text('id').primaryKey(),type:text('type').notNull(),createdAt:text('created_at').notNull()});
export const billingDisputes=sqliteTable('billing_disputes',{id:text('id').primaryKey(),userId:text('user_id').notNull(),orderId:text('order_id').notNull(),status:text('status').notNull(),amountCents:integer('amount_cents').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_billing_disputes_owner').on(t.userId)]);
export const gatewayKeys=sqliteTable('gateway_keys',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),prefix:text('prefix').notNull(),hash:text('hash').notNull().unique(),scopes:text('scopes').notNull(),dailyLimitMicros:integer('daily_limit_micros').notNull(),totalLimitMicros:integer('total_limit_micros').notNull(),expiresAt:text('expires_at').notNull(),revokedAt:text('revoked_at'),createdAt:text('created_at').notNull(),lastUsedAt:text('last_used_at')},t=>[index('idx_gateway_keys_owner').on(t.userId)]);
export const gatewayAccounts=sqliteTable('gateway_accounts',{userId:text('user_id').primaryKey(),dailyLimitMicros:integer('daily_limit_micros').notNull().default(10000000),suspended:integer('suspended').notNull().default(0),updatedAt:text('updated_at').notNull()});
export const gatewayRequests=sqliteTable('gateway_requests',{id:text('id').primaryKey(),userId:text('user_id').notNull(),keyId:text('key_id'),requestKey:text('request_key').notNull(),payloadHash:text('payload_hash').notNull(),capability:text('capability').notNull(),model:text('model').notNull(),rateVersion:text('rate_version').notNull(),state:text('state').notNull(),reservedMicros:integer('reserved_micros').notNull(),costMicros:integer('cost_micros').notNull().default(0),togetherReserved:integer('together_reserved').notNull().default(0),youReserved:integer('you_reserved').notNull().default(0),deepgramReserved:integer('deepgram_reserved').notNull().default(0),togetherCost:integer('together_cost').notNull().default(0),youCost:integer('you_cost').notNull().default(0),deepgramCost:integer('deepgram_cost').notNull().default(0),usageJson:text('usage_json').notNull().default('{}'),resultJson:text('result_json'),errorCode:text('error_code'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),expiresAt:text('expires_at').notNull()},t=>[uniqueIndex('idx_gateway_request_retry').on(t.userId,t.requestKey),index('idx_gateway_request_owner_date').on(t.userId,t.createdAt),index('idx_gateway_request_state').on(t.state,t.updatedAt)]);
export const gatewayOutbox=sqliteTable('gateway_outbox',{id:text('id').primaryKey(),userId:text('user_id').notNull(),requestId:text('request_id').notNull().unique(),payload:text('payload').notNull(),state:text('state').notNull().default('pending'),createdAt:text('created_at').notNull(),exportReceipt:text('export_receipt'),exportedAt:text('exported_at')},t=>[index('idx_gateway_outbox_state').on(t.state,t.createdAt)]);

export const gatewayAudio = sqliteTable('gateway_audio', {
 requestId: text('request_id').notNull(),
 chunkIndex: integer('chunk_index').notNull(),
 content: text('content').notNull(),
 createdAt: text('created_at').notNull(),
}, table => [uniqueIndex('gateway_audio_request_chunk').on(table.requestId, table.chunkIndex), index('gateway_audio_date').on(table.createdAt)]);
