'use client';
import {useEffect,useState} from 'react';
import {nativeApi,NativeApiError} from '@/lib/native-api-client.mjs';
export default function NativeAuthForm({mode}:{mode:'login'|'signup'}){
 const[username,setUsername]=useState(''),[password,setPassword]=useState(''),[email,setEmail]=useState(''),[code,setCode]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setReady(false);setError('');nativeApi('/api/native/auth/self',{signal:controller.signal}).then(()=>location.replace('/api-account/overview')).catch(e=>{if(controller.signal.aborted)return;if(e instanceof NativeApiError&&e.status===401)setReady(true);else setError(e.message)});return()=>controller.abort()},[retry]);
 async function submit(event:React.FormEvent){event.preventDefault();if(!accepted||busy||!ready)return;setBusy(true);setError('');setNotice('');try{
  const body={username:username.trim(),password,acceptedTerms:true,...(mode==='signup'?{...(email.trim()?{email:email.trim()}:{}),...(code.trim()?{verification_code:code.trim()}: {})}:{})};
  await nativeApi('/api/native/auth/'+(mode==='signup'?'register':'login'),{method:'POST',body});
  if(mode==='login')location.assign('/api-account/overview');else setNotice('Your API account was created. Sign in with your chosen username and password.');
 }catch(e){setError((e as Error).message)}finally{setPassword('');setBusy(false)}}
 return <form className="console-form" onSubmit={submit}><label>Username<input required minLength={1} maxLength={64} autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} disabled={busy}/></label>{mode==='signup'&&<><label>Email address<input type="email" maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><label>Email verification code <small>If you have received one</small><input maxLength={254} autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} disabled={busy}/></label></>}<label>Password<input required type="password" minLength={mode==='signup'?8:1} maxLength={mode==='signup'?20:128} autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/>{mode==='signup'&&<small>Use 8–20 characters.</small>}</label><label className="native-checkbox"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} required disabled={busy}/><span>I have reviewed and accept the <a href="/terms" target="_blank" rel="noreferrer">API WILD terms</a> and <a href="/privacy" target="_blank" rel="noreferrer">privacy policy</a>.</span></label>{error&&<div role="alert" className="form-error">{error}{!ready&&<button type="button" onClick={()=>setRetry(v=>v+1)}>Retry connection</button>}</div>}{notice&&<p role="status" className="info-banner">{notice} <a href="/api-account/login">Sign in →</a></p>}<button className="pill-button dark" disabled={busy||!ready||!accepted}>{busy?'Please wait…':!ready?'API access awaiting activation':mode==='login'?'Sign in to API account →':'Create API account →'}</button></form>;
}
